ALTER TABLE tournaments MODIFY COLUMN entry_fee_nano BIGINT NOT NULL DEFAULT 10000000;
ALTER TABLE tournaments MODIFY COLUMN state ENUM('WAITING','DEPOSIT_PHASE','QUESTION_ACTIVE','INTERMISSION','GAME_OVER') NOT NULL DEFAULT 'WAITING';
