INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_index, category, difficulty, content_hash) VALUES
('What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 2, 'Geography', 'Easy', SHA2('What is the capital of France?', 256)),
('Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 1, 'Science', 'Easy', SHA2('Which planet is known as the Red Planet?', 256)),
('Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'William Shakespeare', 'Mark Twain', 'Jane Austen', 1, 'Literature', 'Easy', SHA2('Who wrote "Romeo and Juliet"?', 256)),
('What is the largest ocean on Earth?', 'Atlantic Ocean', 'Indian Ocean', 'Arctic Ocean', 'Pacific Ocean', 3, 'Geography', 'Easy', SHA2('What is the largest ocean on Earth?', 256)),
('What is the chemical symbol for Gold?', 'Ag', 'Fe', 'Au', 'Pb', 2, 'Science', 'Medium', SHA2('What is the chemical symbol for Gold?', 256)),
('In which year did the Titanic sink?', '1910', '1912', '1914', '1916', 1, 'History', 'Medium', SHA2('In which year did the Titanic sink?', 256)),
('What is the smallest prime number?', '0', '1', '2', '3', 2, 'Mathematics', 'Easy', SHA2('What is the smallest prime number?', 256)),
('Who painted the Mona Lisa?', 'Vincent van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Claude Monet', 2, 'Art', 'Easy', SHA2('Who painted the Mona Lisa?', 256)),
('Which country won the FIFA World Cup in 2018?', 'Brazil', 'Germany', 'France', 'Argentina', 2, 'Sports', 'Easy', SHA2('Which country won the FIFA World Cup in 2018?', 256)),
('What is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Platinum', 2, 'Science', 'Easy', SHA2('What is the hardest natural substance on Earth?', 256)),
('Which element has the atomic number 1?', 'Oxygen', 'Helium', 'Hydrogen', 'Nitrogen', 2, 'Science', 'Easy', SHA2('Which element has the atomic number 1?', 256)),
('What is the capital of Japan?', 'Seoul', 'Beijing', 'Tokyo', 'Bangkok', 2, 'Geography', 'Easy', SHA2('What is the capital of Japan?', 256)),
('Who is known as the "Father of Computers"?', 'Alan Turing', 'Charles Babbage', 'Bill Gates', 'Steve Jobs', 1, 'Technology', 'Medium', SHA2('Who is known as the "Father of Computers"?', 256)),
('Which is the longest river in the world?', 'Amazon', 'Nile', 'Yangtze', 'Mississippi', 1, 'Geography', 'Medium', SHA2('Which is the longest river in the world?', 256)),
('What is the currency of the United Kingdom?', 'Euro', 'Dollar', 'Pound Sterling', 'Yen', 2, 'General', 'Easy', SHA2('What is the currency of the United Kingdom?', 256)),
('Which gas do plants absorb from the atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 2, 'Science', 'Easy', SHA2('Which gas do plants absorb from the atmosphere?', 256)),
('Who was the first man to walk on the moon?', 'Yuri Gagarin', 'Buzz Aldrin', 'Neil Armstrong', 'John Glenn', 2, 'History', 'Easy', SHA2('Who was the first man to walk on the moon?', 256)),
('What is the square root of 144?', '10', '11', '12', '13', 2, 'Mathematics', 'Easy', SHA2('What is the square root of 144?', 256)),
('Which country is known as the Land of the Rising Sun?', 'China', 'Japan', 'South Korea', 'Thailand', 1, 'Geography', 'Easy', SHA2('Which country is known as the Land of the Rising Sun?', 256)),
('Who wrote the "Harry Potter" series?', 'J.R.R. Tolkien', 'C.S. Lewis', 'J.K. Rowling', 'Stephen King', 2, 'Literature', 'Easy', SHA2('Who wrote the "Harry Potter" series?', 256)),
('What is the largest mammal in the world?', 'Elephant', 'Blue Whale', 'Giraffe', 'Great White Shark', 1, 'Science', 'Easy', SHA2('What is the largest mammal in the world?', 256)),
('Which organ in the human body is responsible for pumping blood?', 'Lungs', 'Brain', 'Heart', 'Kidneys', 2, 'Science', 'Easy', SHA2('Which organ in the human body is responsible for pumping blood?', 256)),
('What is the capital of Italy?', 'Venice', 'Florence', 'Rome', 'Milan', 2, 'Geography', 'Easy', SHA2('What is the capital of Italy?', 256)),
('Who discovered penicillin?', 'Marie Curie', 'Thomas Edison', 'Alexander Fleming', 'Albert Einstein', 2, 'Science', 'Medium', SHA2('Who discovered penicillin?', 256)),
('Which planet is the largest in our solar system?', 'Earth', 'Mars', 'Jupiter', 'Saturn', 2, 'Science', 'Easy', SHA2('Which planet is the largest in our solar system?', 256)),
('In which continent is the Sahara Desert located?', 'Asia', 'Africa', 'South America', 'Australia', 1, 'Geography', 'Easy', SHA2('In which continent is the Sahara Desert located?', 256)),
('What is the main ingredient in guacamole?', 'Tomato', 'Onion', 'Avocado', 'Garlic', 2, 'General', 'Easy', SHA2('What is the main ingredient in guacamole?', 256)),
('Who was the first President of the United States?', 'Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams', 2, 'History', 'Easy', SHA2('Who was the first President of the United States?', 256)),
('Which metal is liquid at room temperature?', 'Silver', 'Mercury', 'Copper', 'Aluminum', 1, 'Science', 'Medium', SHA2('Which metal is liquid at room temperature?', 256)),
('What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 2, 'Geography', 'Medium', SHA2('What is the capital of Australia?', 256)),
('Who developed the theory of relativity?', 'Isaac Newton', 'Nikola Tesla', 'Albert Einstein', 'Stephen Hawking', 2, 'Science', 'Medium', SHA2('Who developed the theory of relativity?', 256)),
('Which is the largest country in the world by area?', 'USA', 'China', 'Russia', 'Canada', 2, 'Geography', 'Easy', SHA2('Which is the largest country in the world by area?', 256)),
('What is the boiling point of water at sea level in Celsius?', '90', '100', '110', '120', 1, 'Science', 'Easy', SHA2('What is the boiling point of water at sea level in Celsius?', 256)),
('Which bird is the symbol of peace?', 'Eagle', 'Owl', 'Dove', 'Sparrow', 2, 'General', 'Easy', SHA2('Which bird is the symbol of peace?', 256)),
('Who invented the light bulb?', 'Nikola Tesla', 'Alexander Graham Bell', 'Thomas Edison', 'Benjamin Franklin', 2, 'Science', 'Easy', SHA2('Who invented the light bulb?', 256)),
('What is the capital of Canada?', 'Toronto', 'Vancouver', 'Ottawa', 'Montreal', 2, 'Geography', 'Medium', SHA2('What is the capital of Canada?', 256)),
('Which is the smallest continent by land area?', 'Europe', 'Africa', 'Australia', 'Antarctica', 2, 'Geography', 'Easy', SHA2('Which is the smallest continent by land area?', 256)),
('Who wrote "The Great Gatsby"?', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'William Faulkner', 'John Steinbeck', 1, 'Literature', 'Medium', SHA2('Who wrote "The Great Gatsby"?', 256)),
('What is the most populous country in the world?', 'USA', 'India', 'China', 'Russia', 1, 'Geography', 'Easy', SHA2('What is the most populous country in the world?', 256)),
('Which ocean is between Africa and Australia?', 'Atlantic', 'Pacific', 'Indian', 'Arctic', 2, 'Geography', 'Medium', SHA2('Which ocean is between Africa and Australia?', 256)),
('What is the main gas found in the air we breathe?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon', 2, 'Science', 'Medium', SHA2('What is the main gas found in the air we breathe?', 256)),
('Who was the first woman to win a Nobel Prize?', 'Rosalind Franklin', 'Ada Lovelace', 'Marie Curie', 'Dorothy Hodgkin', 2, 'Science', 'Medium', SHA2('Who was the first woman to win a Nobel Prize?', 256)),
('What is the capital of Egypt?', 'Alexandria', 'Luxor', 'Cairo', 'Giza', 2, 'Geography', 'Easy', SHA2('What is the capital of Egypt?', 256)),
('Which planet is closest to the Sun?', 'Venus', 'Earth', 'Mercury', 'Mars', 2, 'Science', 'Easy', SHA2('Which planet is closest to the Sun?', 256)),
('Who is the author of "1984"?', 'Aldous Huxley', 'George Orwell', 'Ray Bradbury', 'H.G. Wells', 1, 'Literature', 'Medium', SHA2('Who is the author of "1984"?', 256)),
('What is the currency of Japan?', 'Won', 'Yuan', 'Yen', 'Ringgit', 2, 'General', 'Easy', SHA2('What is the currency of Japan?', 256)),
('Which bone is the longest in the human body?', 'Spine', 'Skull', 'Femur', 'Humerus', 2, 'Science', 'Medium', SHA2('Which bone is the longest in the human body?', 256)),
('What is the capital of Brazil?', 'Rio de Janeiro', 'Sao Paulo', 'Brasilia', 'Salvador', 2, 'Geography', 'Medium', SHA2('What is the capital of Brazil?', 256)),
('Who painted the Sistine Chapel ceiling?', 'Leonardo da Vinci', 'Raphael', 'Michelangelo', 'Donatello', 2, 'Art', 'Medium', SHA2('Who painted the Sistine Chapel ceiling?', 256)),
('Which is the tallest mountain in the world?', 'K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse', 2, 'Geography', 'Easy', SHA2('Which is the tallest mountain in the world?', 256)),
('What is the national animal of India?', 'Lion', 'Elephant', 'Bengal Tiger', 'Leopard', 2, 'General', 'Easy', SHA2('What is the national animal of India?', 256)),
('Who composed the "Moonlight Sonata"?', 'Mozart', 'Beethoven', 'Bach', 'Chopin', 1, 'Music', 'Medium', SHA2('Who composed the "Moonlight Sonata"?', 256)),
('What is the capital of Russia?', 'Saint Petersburg', 'Kiev', 'Moscow', 'Minsk', 2, 'Geography', 'Easy', SHA2('What is the capital of Russia?', 256)),
('Which organ removes waste from the blood?', 'Heart', 'Lungs', 'Kidneys', 'Liver', 2, 'Science', 'Medium', SHA2('Which organ removes waste from the blood?', 256)),
('What is the symbol for the element Oxygen?', 'Ox', 'O', 'O2', 'G', 1, 'Science', 'Easy', SHA2('What is the symbol for the element Oxygen?', 256)),
('Who wrote "The Catcher in the Rye"?', 'J.D. Salinger', 'Jack Kerouac', 'Truman Capote', 'Allen Ginsberg', 0, 'Literature', 'Medium', SHA2('Who wrote "The Catcher in the Rye"?', 256)),
('What is the fastest land animal?', 'Lion', 'Leopard', 'Cheetah', 'Antelope', 2, 'Science', 'Easy', SHA2('What is the fastest land animal?', 256)),
('Which is the largest desert in the world?', 'Sahara', 'Gobi', 'Antarctic', 'Arctic', 2, 'Geography', 'Hard', SHA2('Which is the largest desert in the world?', 256)),
('Who invented the telephone?', 'Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Guglielmo Marconi', 2, 'Science', 'Easy', SHA2('Who invented the telephone?', 256)),
('What is the capital of Germany?', 'Munich', 'Hamburg', 'Berlin', 'Frankfurt', 2, 'Geography', 'Easy', SHA2('What is the capital of Germany?', 256)),
('Which planet has the most moons?', 'Mars', 'Jupiter', 'Saturn', 'Neptune', 2, 'Science', 'Medium', SHA2('Which planet has the most moons?', 256)),
('Who wrote the "Odyssey"?', 'Socrates', 'Plato', 'Homer', 'Aristotle', 2, 'Literature', 'Medium', SHA2('Who wrote the "Odyssey"?', 256)),
('What is the capital of Spain?', 'Barcelona', 'Seville', 'Madrid', 'Valencia', 2, 'Geography', 'Easy', SHA2('What is the capital of Spain?', 256)),
('Which is the most widely spoken language in the world?', 'Spanish', 'Hindi', 'Mandarin Chinese', 'English', 3, 'General', 'Medium', SHA2('Which is the most widely spoken language in the world?', 256)),
('What is the center of an atom called?', 'Electron', 'Proton', 'Nucleus', 'Neutron', 2, 'Science', 'Medium', SHA2('What is the center of an atom called?', 256)),
('Who painted "The Starry Night"?', 'Claude Monet', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dali', 2, 'Art', 'Medium', SHA2('Who painted "The Starry Night"?', 256)),
('What is the capital of South Korea?', 'Busan', 'Incheon', 'Seoul', 'Daegu', 2, 'Geography', 'Easy', SHA2('What is the capital of South Korea?', 256)),
('Which country is known as the Land of a Thousand Lakes?', 'Norway', 'Sweden', 'Finland', 'Denmark', 2, 'Geography', 'Medium', SHA2('Which country is known as the Land of a Thousand Lakes?', 256)),
('Who discovered gravity?', 'Albert Einstein', 'Galileo Galilei', 'Isaac Newton', 'Johannes Kepler', 2, 'Science', 'Easy', SHA2('Who discovered gravity?', 256)),
('What is the capital of Argentina?', 'Santiago', 'Montevideo', 'Buenos Aires', 'Lima', 2, 'Geography', 'Easy', SHA2('What is the capital of Argentina?', 256)),
('Which animal is known as the Ship of the Desert?', 'Horse', 'Donkey', 'Camel', 'Elephant', 2, 'General', 'Easy', SHA2('Which animal is known as the Ship of the Desert?', 256)),
('What is the largest planet in our solar system?', 'Saturn', 'Neptune', 'Jupiter', 'Uranus', 2, 'Science', 'Easy', SHA2('What is the largest planet in our solar system?', 256)),
('Who was the lead singer of Queen?', 'John Lennon', 'Mick Jagger', 'Freddie Mercury', 'David Bowie', 2, 'Music', 'Easy', SHA2('Who was the lead singer of Queen?', 256)),
('What is the capital of Mexico?', 'Guadalajara', 'Cancun', 'Mexico City', 'Monterrey', 2, 'Geography', 'Easy', SHA2('What is the capital of Mexico?', 256)),
('Which element is represented by the symbol Fe?', 'Fluorine', 'Fermium', 'Iron', 'Francium', 2, 'Science', 'Medium', SHA2('Which element is represented by the symbol Fe?', 256)),
('Who wrote "The Lord of the Rings"?', 'C.S. Lewis', 'Roald Dahl', 'J.R.R. Tolkien', 'George R.R. Martin', 2, 'Literature', 'Easy', SHA2('Who wrote "The Lord of the Rings"?', 256)),
('What is the capital of Turkey?', 'Istanbul', 'Izmir', 'Ankara', 'Antalya', 2, 'Geography', 'Medium', SHA2('What is the capital of Turkey?', 256)),
('Which is the largest internal organ in the human body?', 'Brain', 'Lungs', 'Liver', 'Heart', 2, 'Science', 'Medium', SHA2('Which is the largest internal organ in the human body?', 256)),
('What is the capital of Thailand?', 'Phuket', 'Chiang Mai', 'Bangkok', 'Pattaya', 2, 'Geography', 'Easy', SHA2('What is the capital of Thailand?', 256)),
('Who was known as the "Maid of Orleans"?', 'Queen Elizabeth I', 'Marie Antoinette', 'Joan of Arc', 'Catherine the Great', 2, 'History', 'Medium', SHA2('Who was known as the "Maid of Orleans"?', 256)),
('What is the chemical symbol for Silver?', 'Si', 'Sl', 'Ag', 'Sv', 2, 'Science', 'Medium', SHA2('What is the chemical symbol for Silver?', 256)),
('Which is the smallest country in the world?', 'Monaco', 'San Marino', 'Vatican City', 'Liechtenstein', 2, 'Geography', 'Easy', SHA2('Which is the smallest country in the world?', 256)),
('Who won the first ever Nobel Prize in Physics?', 'Marie Curie', 'Wilhelm Conrad Rontgen', 'Max Planck', 'Ernest Rutherford', 1, 'Science', 'Hard', SHA2('Who won the first ever Nobel Prize in Physics?', 256)),
('What is the capital of Norway?', 'Bergen', 'Stavanger', 'Oslo', 'Trondheim', 2, 'Geography', 'Easy', SHA2('What is the capital of Norway?', 256)),
('Which country is home to the Kangaroo?', 'New Zealand', 'South Africa', 'Australia', 'Brazil', 2, 'General', 'Easy', SHA2('Which country is home to the Kangaroo?', 256)),
('Who wrote "To Kill a Mockingbird"?', 'John Steinbeck', 'Harper Lee', 'Ernest Hemingway', 'William Faulkner', 1, 'Literature', 'Medium', SHA2('Who wrote "To Kill a Mockingbird"?', 256)),
('What is the capital of Sweden?', 'Gothenburg', 'Malmo', 'Stockholm', 'Uppsala', 2, 'Geography', 'Medium', SHA2('What is the capital of Sweden?', 256)),
('Which element has the symbol He?', 'Hydrogen', 'Hafnium', 'Helium', 'Mercury', 2, 'Science', 'Easy', SHA2('Which element has the symbol He?', 256)),
('Who is the Greek god of the sea?', 'Zeus', 'Hades', 'Poseidon', 'Apollo', 2, 'Mythology', 'Easy', SHA2('Who is the Greek god of the sea?', 256)),
('What is the capital of Switzerland?', 'Zurich', 'Geneva', 'Bern', 'Basel', 2, 'Geography', 'Medium', SHA2('What is the capital of Switzerland?', 256)),
('Which is the coldest planet in our solar system?', 'Neptune', 'Saturn', 'Uranus', 'Pluto', 2, 'Science', 'Hard', SHA2('Which is the coldest planet in our solar system?', 256)),
('Who wrote "The Hobbit"?', 'George R.R. Martin', 'Stephen King', 'J.R.R. Tolkien', 'J.K. Rowling', 2, 'Literature', 'Easy', SHA2('Who wrote "The Hobbit"?', 256)),
('What is the capital of Portugal?', 'Porto', 'Braga', 'Lisbon', 'Faro', 2, 'Geography', 'Easy', SHA2('What is the capital of Portugal?', 256)),
('Which gas is most abundant in the Earth’s atmosphere?', 'Oxygen', 'Argon', 'Nitrogen', 'Carbon Dioxide', 2, 'Science', 'Medium', SHA2('Which gas is most abundant in the Earth’s atmosphere?', 256)),
('Who painted the "The Persistence of Memory"?', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dali', 'Henri Matisse', 2, 'Art', 'Medium', SHA2('Who painted the "The Persistence of Memory"?', 256)),
('What is the capital of Greece?', 'Sparta', 'Thessaloniki', 'Athens', 'Rhodes', 2, 'Geography', 'Easy', SHA2('What is the capital of Greece?', 256)),
('Which animal is the largest bird in the world?', 'Eagle', 'Emu', 'Ostrich', 'Penguin', 2, 'Science', 'Easy', SHA2('Which animal is the largest bird in the world?', 256)),
('Who discovered Pluto?', 'Edwin Hubble', 'Carl Sagan', 'Clyde Tombaugh', 'Isaac Newton', 2, 'Science', 'Hard', SHA2('Who discovered Pluto?', 256)),
('What is the capital of New Zealand?', 'Auckland', 'Christchurch', 'Wellington', 'Hamilton', 2, 'Geography', 'Medium', SHA2('What is the capital of New Zealand?', 256)),
('Which mountain range includes Mount Everest?', 'Andes', 'Rockies', 'Himalayas', 'Alps', 2, 'Geography', 'Easy', SHA2('Which mountain range includes Mount Everest?', 256)),
('Who wrote "A Tale of Two Cities"?', 'Mark Twain', 'Leo Tolstoy', 'Charles Dickens', 'Victor Hugo', 2, 'Literature', 'Medium', SHA2('Who wrote "A Tale of Two Cities"?', 256)),
('What is the capital of India?', 'Mumbai', 'Kolkata', 'New Delhi', 'Chennai', 2, 'Geography', 'Easy', SHA2('What is the capital of India?', 256)),
('Which planet is known as the "Morning Star"?', 'Mars', 'Jupiter', 'Venus', 'Mercury', 2, 'Science', 'Medium', SHA2('Which planet is known as the "Morning Star"?', 256)),
('Who is the Roman god of war?', 'Jupiter', 'Neptune', 'Mars', 'Mercury', 2, 'Mythology', 'Easy', SHA2('Who is the Roman god of war?', 256)),
('What is the capital of South Africa?', 'Johannesburg', 'Durban', 'Pretoria', 'Port Elizabeth', 2, 'Geography', 'Medium', SHA2('What is the capital of South Africa?', 256)),
('Which is the largest island in the world?', 'Australia', 'New Guinea', 'Greenland', 'Borneo', 2, 'Geography', 'Medium', SHA2('Which is the largest island in the world?', 256)),
('Who composed the "Four Seasons"?', 'Bach', 'Handel', 'Vivaldi', 'Haydn', 2, 'Music', 'Medium', SHA2('Who composed the "Four Seasons"?', 256)),
('What is the capital of Ireland?', 'Belfast', 'Cork', 'Dublin', 'Galway', 2, 'Geography', 'Easy', SHA2('What is the capital of Ireland?', 256)),
('Which is the smallest planet in our solar system?', 'Mars', 'Venus', 'Mercury', 'Earth', 2, 'Science', 'Easy', SHA2('Which is the smallest planet in our solar system?', 256)),
('Who wrote "Pride and Prejudice"?', 'Charlotte Bronte', 'Emily Bronte', 'Jane Austen', 'Mary Shelley', 2, 'Literature', 'Medium', SHA2('Who wrote "Pride and Prejudice"?', 256)),
('What is the capital of Chile?', 'Valparaiso', 'Concepcion', 'Santiago', 'Antofagasta', 2, 'Geography', 'Medium', SHA2('What is the capital of Chile?', 256)),
('What is the capital of Peru?', 'Cusco', 'Arequipa', 'Lima', 'Trujillo', 2, 'Geography', 'Easy', SHA2('What is the capital of Peru?', 256)),
('Which element has the atomic number 6?', 'Oxygen', 'Carbon', 'Nitrogen', 'Boron', 1, 'Science', 'Medium', SHA2('Which element has the atomic number 6?', 256)),
('Who wrote "The Communist Manifesto"?', 'Karl Marx', 'Friedrich Engels', 'Vladimir Lenin', 'Both A and B', 3, 'History', 'Medium', SHA2('Who wrote "The Communist Manifesto"?', 256)),
('What is the capital of Canada?', 'Montreal', 'Toronto', 'Ottawa', 'Vancouver', 2, 'Geography', 'Easy', SHA2('What is the capital of Canada?', 256)),
('Which is the largest internal organ?', 'Brain', 'Liver', 'Lungs', 'Heart', 1, 'Science', 'Medium', SHA2('Which is the largest internal organ?', 256)),
('What is the square root of 64?', '6', '7', '8', '9', 2, 'Mathematics', 'Easy', SHA2('What is the square root of 64?', 256)),
('Who is known as the "Father of Evolution"?', 'Charles Darwin', 'Gregor Mendel', 'Lamarck', 'Alfred Wallace', 0, 'Science', 'Easy', SHA2('Who is known as the "Father of Evolution"?', 256)),
('What is the capital of Russia?', 'Moscow', 'Saint Petersburg', 'Kiev', 'Minsk', 0, 'Geography', 'Easy', SHA2('What is the capital of Russia?', 256)),
('Which planet is known as the "Evening Star"?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 0, 'Science', 'Medium', SHA2('Which planet is known as the "Evening Star"?', 256)),
('Who wrote "Crime and Punishment"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Turgenev', 1, 'Literature', 'Medium', SHA2('Who wrote "Crime and Punishment"?', 256)),
('What is the capital of South Africa?', 'Cape Town', 'Pretoria', 'Bloemfontein', 'All of the above', 3, 'Geography', 'Medium', SHA2('What is the capital of South Africa?', 256)),
('Which is the largest desert in Africa?', 'Sahara', 'Kalahari', 'Namib', 'Libyan', 0, 'Geography', 'Easy', SHA2('Which is the largest desert in Africa?', 256)),
('Who founded the Mongol Empire?', 'Kublai Khan', 'Genghis Khan', 'Tamerlane', 'Batu Khan', 1, 'History', 'Medium', SHA2('Who founded the Mongol Empire?', 256)),
('What is the capital of Iceland?', 'Reykjavik', 'Akureyri', 'Keflavik', 'Vik', 0, 'Geography', 'Medium', SHA2('What is the capital of Iceland?', 256)),
('Which gas is known as "Laughing Gas"?', 'Nitric Oxide', 'Nitrous Oxide', 'Nitrogen Dioxide', 'Ammonia', 1, 'Science', 'Medium', SHA2('Which gas is known as "Laughing Gas"?', 256)),
('Who painted "The Last Supper"?', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello', 2, 'Art', 'Easy', SHA2('Who painted "The Last Supper"?', 256)),
('What is the capital of Kenya?', 'Mombasa', 'Nairobi', 'Kisumu', 'Nakuru', 1, 'Geography', 'Easy', SHA2('What is the capital of Kenya?', 256)),
('Which is the smallest bone in the human body?', 'Stapes', 'Hamate', 'Patella', 'Incus', 0, 'Science', 'Hard', SHA2('Which is the smallest bone in the human body?', 256)),
('Who wrote "The Iliad"?', 'Socrates', 'Aristotle', 'Homer', 'Sophocles', 2, 'Literature', 'Medium', SHA2('Who wrote "The Iliad"?', 256)),
('What is the capital of Vietnam?', 'Ho Chi Minh City', 'Hanoi', 'Da Nang', 'Hue', 1, 'Geography', 'Medium', SHA2('What is the capital of Vietnam?', 256)),
('Which metal is the best conductor of electricity?', 'Gold', 'Silver', 'Copper', 'Aluminum', 1, 'Science', 'Medium', SHA2('Which metal is the best conductor of electricity?', 256)),
('Who is the author of "The Divine Comedy"?', 'Petrarch', 'Boccaccio', 'Dante Alighieri', 'Machiavelli', 2, 'Literature', 'Hard', SHA2('Who is the author of "The Divine Comedy"?', 256)),
('What is the capital of Saudi Arabia?', 'Jeddah', 'Mecca', 'Riyadh', 'Medina', 2, 'Geography', 'Medium', SHA2('What is the capital of Saudi Arabia?', 256)),
('Which is the largest lake in Africa?', 'Lake Tanganyika', 'Lake Malawi', 'Lake Victoria', 'Lake Chad', 2, 'Geography', 'Medium', SHA2('Which is the largest lake in Africa?', 256)),
('Who was the primary author of the Declaration of Independence?', 'John Adams', 'Benjamin Franklin', 'Thomas Jefferson', 'James Madison', 2, 'History', 'Medium', SHA2('Who was the primary author of the Declaration of Independence?', 256)),
('What is the capital of Poland?', 'Krakow', 'Warsaw', 'Gdansk', 'Poznan', 1, 'Geography', 'Medium', SHA2('What is the capital of Poland?', 256)),
('Which subatomic particle has no charge?', 'Proton', 'Electron', 'Neutron', 'Positron', 2, 'Science', 'Easy', SHA2('Which subatomic particle has no charge?', 256)),
('Who wrote "The Odyssey"?', 'Aeschylus', 'Euripides', 'Homer', 'Hesiod', 2, 'Literature', 'Medium', SHA2('Who wrote "The Odyssey"?', 256)),
('What is the capital of Cuba?', 'Santiago de Cuba', 'Havana', 'Camaguey', 'Holguin', 1, 'Geography', 'Easy', SHA2('What is the capital of Cuba?', 256)),
('Which planet is famous for its rings?', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 1, 'Science', 'Easy', SHA2('Which planet is famous for its rings?', 256)),
('Who painted "Guerica"?', 'Salvador Dali', 'Joan Miro', 'Pablo Picasso', 'Francisco Goya', 2, 'Art', 'Medium', SHA2('Who painted "Guerica"?', 256)),
('What is the capital of Finland?', 'Tampere', 'Turku', 'Helsinki', 'Espoo', 2, 'Geography', 'Easy', SHA2('What is the capital of Finland?', 256)),
('Which is the largest bird in North America?', 'Bald Eagle', 'California Condor', 'Golden Eagle', 'Turkey Vulture', 1, 'Science', 'Hard', SHA2('Which is the largest bird in North America?', 256)),
('Who wrote "War and Peace"?', 'Fyodor Dostoevsky', 'Leo Tolstoy', 'Anton Chekhov', 'Ivan Bunin', 1, 'Literature', 'Medium', SHA2('Who wrote "War and Peace"?', 256)),
('What is the capital of Morocco?', 'Casablanca', 'Marrakech', 'Rabat', 'Fes', 2, 'Geography', 'Medium', SHA2('What is the capital of Morocco?', 256)),
('Which chemical element has the symbol K?', 'Krypton', 'Potassium', 'Kalium', 'Kryptite', 1, 'Science', 'Medium', SHA2('Which chemical element has the symbol K?', 256)),
('Who is the lead guitarist of Led Zeppelin?', 'Eric Clapton', 'Jeff Beck', 'Jimmy Page', 'Keith Richards', 2, 'Music', 'Medium', SHA2('Who is the lead guitarist of Led Zeppelin?', 256)),
('What is the capital of Austria?', 'Salzburg', 'Innsbruck', 'Vienna', 'Linz', 2, 'Geography', 'Easy', SHA2('What is the capital of Austria?', 256)),
('Which is the most dense planet in our solar system?', 'Earth', 'Jupiter', 'Mars', 'Mercury', 0, 'Science', 'Hard', SHA2('Which is the most dense planet in our solar system?', 256)),
('Who wrote "Les Miserables"?', 'Gustave Flaubert', 'Victor Hugo', 'Alexandre Dumas', 'Honore de Balzac', 1, 'Literature', 'Medium', SHA2('Who wrote "Les Miserables"?', 256)),
('What is the capital of Ukraine?', 'Lviv', 'Odessa', 'Kyiv', 'Kharkiv', 2, 'Geography', 'Easy', SHA2('What is the capital of Ukraine?', 256)),
('Which is the largest cat species in the world?', 'Lion', 'Leopard', 'Tiger', 'Jaguar', 2, 'Science', 'Medium', SHA2('Which is the largest cat species in the world?', 256)),
('Who was the first woman in space?', 'Sally Ride', 'Valentina Tereshkova', 'Svetlana Savitskaya', 'Mae Jemison', 1, 'History', 'Medium', SHA2('Who was the first woman in space?', 256)),
('What is the capital of Hungary?', 'Debrecen', 'Szeged', 'Budapest', 'Miskolc', 2, 'Geography', 'Medium', SHA2('What is the capital of Hungary?', 256)),
('Which element is found in all organic compounds?', 'Oxygen', 'Hydrogen', 'Carbon', 'Nitrogen', 2, 'Science', 'Easy', SHA2('Which element is found in all organic compounds?', 256)),
('Who wrote "Don Quixote"?', 'Gabriel Garcia Marquez', 'Miguel de Cervantes', 'Jorge Luis Borges', 'Isabel Allende', 1, 'Literature', 'Medium', SHA2('Who wrote "Don Quixote"?', 256)),
('What is the capital of Pakistan?', 'Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 2, 'Geography', 'Medium', SHA2('What is the capital of Pakistan?', 256)),
('Which is the longest mountain range on land?', 'Himalayas', 'Rockies', 'Andes', 'Alps', 2, 'Geography', 'Medium', SHA2('Which is the longest mountain range on land?', 256)),
('Who won the Nobel Prize in Literature in 2016?', 'Alice Munro', 'Bob Dylan', 'Kazuo Ishiguro', 'Patrick Modiano', 1, 'Literature', 'Hard', SHA2('Who won the Nobel Prize in Literature in 2016?', 256)),
('What is the capital of Israel?', 'Tel Aviv', 'Jerusalem', 'Haifa', 'Ashdod', 1, 'Geography', 'Medium', SHA2('What is the capital of Israel?', 256)),
('Which gas makes up 21% of Earth’s atmosphere?', 'Nitrogen', 'Oxygen', 'Carbon Dioxide', 'Argon', 1, 'Science', 'Easy', SHA2('Which gas makes up 21% of Earth’s atmosphere?', 256)),
('Who wrote "The Brothers Karamazov"?', 'Fyodor Dostoevsky', 'Leo Tolstoy', 'Ivan Turgenev', 'Nikolai Gogol', 0, 'Literature', 'Hard', SHA2('Who wrote "The Brothers Karamazov"?', 256)),
('What is the capital of Colombia?', 'Medellin', 'Cali', 'Bogota', 'Barranquilla', 2, 'Geography', 'Easy', SHA2('What is the capital of Colombia?', 256)),
('Which is the smallest primary color in the additive color model?', 'Red', 'Green', 'Blue', 'Yellow', 2, 'Physics', 'Medium', SHA2('Which is the smallest primary color in the additive color model?', 256)),
('Who developed the polio vaccine?', 'Louis Pasteur', 'Jonas Salk', 'Edward Jenner', 'Robert Koch', 1, 'Science', 'Medium', SHA2('Who developed the polio vaccine?', 256)),
('What is the capital of Portugal?', 'Porto', 'Lisbon', 'Coimbra', 'Braga', 1, 'Geography', 'Easy', SHA2('What is the capital of Portugal?', 256)),
('Which planet is known as the "Ice Giant"?', 'Saturn', 'Jupiter', 'Neptune', 'Mars', 2, 'Science', 'Medium', SHA2('Which planet is known as the "Ice Giant"?', 256)),
('Who wrote "Uncle Tom''s Cabin"?', 'Mark Twain', 'Nathaniel Hawthorne', 'Harriet Beecher Stowe', 'Herman Melville', 2, 'Literature', 'Medium', SHA2('Who wrote "Uncle Tom''s Cabin"?', 256)),
('What is the capital of Sweden?', 'Gothenburg', 'Stockholm', 'Malmo', 'Uppsala', 1, 'Geography', 'Easy', SHA2('What is the capital of Sweden?', 256)),
('Which is the largest country in South America by area?', 'Argentina', 'Colombia', 'Brazil', 'Peru', 2, 'Geography', 'Easy', SHA2('Which is the largest country in South America by area?', 256)),
('Who painted "The Night Watch"?', 'Jan Vermeer', 'Rembrandt', 'Frans Hals', 'Piet Mondrian', 1, 'Art', 'Hard', SHA2('Who painted "The Night Watch"?', 256)),
('What is the capital of Belgium?', 'Antwerp', 'Ghent', 'Brussels', 'Bruges', 2, 'Geography', 'Easy', SHA2('What is the capital of Belgium?', 256)),
('Which chemical element has the symbol Sn?', 'Zinc', 'Tin', 'Lead', 'Antimony', 1, 'Science', 'Medium', SHA2('Which chemical element has the symbol Sn?', 256)),
('Who won the first FIFA World Cup in 1930?', 'Brazil', 'Argentina', 'Uruguay', 'Italy', 2, 'Sports', 'Medium', SHA2('Who won the first FIFA World Cup in 1930?', 256)),
('What is the capital of Romania?', 'Cluj-Napoca', 'Timisoara', 'Bucharest', 'Iasi', 2, 'Geography', 'Medium', SHA2('What is the capital of Romania?', 256)),
('Which is the most common element in the universe?', 'Oxygen', 'Carbon', 'Hydrogen', 'Helium', 2, 'Science', 'Medium', SHA2('Which is the most common element in the universe?', 256)),
('Who wrote "The Old Man and the Sea"?', 'F. Scott Fitzgerald', 'Ernest Hemingway', 'John Steinbeck', 'William Faulkner', 1, 'Literature', 'Easy', SHA2('Who wrote "The Old Man and the Sea"?', 256)),
('What is the capital of Czech Republic?', 'Brno', 'Ostrava', 'Prague', 'Plzen', 2, 'Geography', 'Easy', SHA2('What is the capital of Czech Republic?', 256)),
('Which planet rotates on its side?', 'Saturn', 'Jupiter', 'Uranus', 'Neptune', 2, 'Science', 'Hard', SHA2('Which planet rotates on its side?', 256)),
('Who was the first person to reach the South Pole?', 'Robert Falcon Scott', 'Roald Amundsen', 'Ernest Shackleton', 'Richard Byrd', 1, 'History', 'Hard', SHA2('Who was the first person to reach the South Pole?', 256)),
('What is the capital of Denmark?', 'Aarhus', 'Odense', 'Copenhagen', 'Aalborg', 2, 'Geography', 'Easy', SHA2('What is the capital of Denmark?', 256)),
('Which metal is known as the "King of Metals"?', 'Gold', 'Silver', 'Platinum', 'Iron', 0, 'Science', 'Medium', SHA2('Which metal is known as the "King of Metals"?', 256)),
('Who wrote "Waiting for Godot"?', 'Eugene Ionesco', 'Samuel Beckett', 'Harold Pinter', 'Jean Genet', 1, 'Literature', 'Hard', SHA2('Who wrote "Waiting for Godot"?', 256)),
('What is the capital of Malaysia?', 'Penang', 'Johor Bahru', 'Kuala Lumpur', 'Ipoh', 2, 'Geography', 'Easy', SHA2('What is the capital of Malaysia?', 256)),
('Which is the largest moon of Saturn?', 'Titan', 'Enceladus', 'Rhea', 'Dione', 0, 'Science', 'Medium', SHA2('Which is the largest moon of Saturn?', 256)),
('Who discovered the structure of DNA?', 'Francis Crick', 'James Watson', 'Rosalind Franklin', 'All of the above', 3, 'Science', 'Medium', SHA2('Who discovered the structure of DNA?', 256)),
('What is the capital of Iran?', 'Isfahan', 'Shiraz', 'Tehran', 'Mashhad', 2, 'Geography', 'Easy', SHA2('What is the capital of Iran?', 256)),
('Which is the only continent with no active volcanoes?', 'Europe', 'Australia', 'Africa', 'Antarctica', 1, 'Geography', 'Hard', SHA2('Which is the only continent with no active volcanoes?', 256)),
('Who wrote "Life of Pi"?', 'Yann Martel', 'Aravind Adiga', 'Salman Rushdie', 'Rohinton Mistry', 0, 'Literature', 'Medium', SHA2('Who wrote "Life of Pi"?', 256)),
('What is the capital of Iraq?', 'Mosul', 'Basra', 'Baghdad', 'Erbil', 2, 'Geography', 'Easy', SHA2('What is the capital of Iraq?', 256)),
('Which element is the primary component of glass?', 'Carbon', 'Silicon', 'Oxygen', 'Aluminum', 1, 'Science', 'Medium', SHA2('Which element is the primary component of glass?', 256)),
('Who was the first female Prime Minister of the UK?', 'Theresa May', 'Margaret Thatcher', 'Nicola Sturgeon', 'Angela Merkel', 1, 'History', 'Easy', SHA2('Who was the first female Prime Minister of the UK?', 256)),
('What is the capital of Bangladesh?', 'Chittagong', 'Khulna', 'Dhaka', 'Sylhet', 2, 'Geography', 'Easy', SHA2('What is the capital of Bangladesh?', 256)),
('Which planet has the strongest magnetic field?', 'Earth', 'Jupiter', 'Saturn', 'Neptune', 1, 'Science', 'Hard', SHA2('Which planet has the strongest magnetic field?', 256)),
('Who wrote "Brave New World"?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'Philip K. Dick', 1, 'Literature', 'Medium', SHA2('Who wrote "Brave New World"?', 256)),
('What is the capital of Ethiopia?', 'Addis Ababa', 'Dire Dawa', 'Mekele', 'Gondar', 0, 'Geography', 'Medium', SHA2('What is the capital of Ethiopia?', 256)),
('Which is the longest river in Asia?', 'Yellow River', 'Mekong', 'Yangtze', 'Indus', 2, 'Geography', 'Hard', SHA2('Which is the longest river in Asia?', 256)),
('Who painted "Lady with an Ermine"?', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 'Donatello', 2, 'Art', 'Medium', SHA2('Who painted "Lady with an Ermine"?', 256)),
('What is the capital of Uzbekistan?', 'Samarkand', 'Bukhara', 'Tashkent', 'Khiva', 2, 'Geography', 'Medium', SHA2('What is the capital of Uzbekistan?', 256)),
('Which subatomic particle has a positive charge?', 'Electron', 'Neutron', 'Proton', 'Quark', 2, 'Science', 'Easy', SHA2('Which subatomic particle has a positive charge?', 256)),
('Who wrote "The Stranger"?', 'Jean-Paul Sartre', 'Albert Camus', 'Simone de Beauvoir', 'Marcel Proust', 1, 'Literature', 'Medium', SHA2('Who wrote "The Stranger"?', 256)),
('What is the capital of Kazakhstan?', 'Almaty', 'Astana', 'Shymkent', 'Karaganda', 1, 'Geography', 'Medium', SHA2('What is the capital of Kazakhstan?', 256)),
('Which is the largest species of shark?', 'Great White Shark', 'Whale Shark', 'Hammerhead Shark', 'Tiger Shark', 1, 'Science', 'Easy', SHA2('Which is the largest species of shark?', 256)),
('Who was the first person to sail around the world?', 'Christopher Columbus', 'Ferdinand Magellan', 'Vasco da Gama', 'James Cook', 1, 'History', 'Medium', SHA2('Who was the first person to sail around the world?', 256)),
('What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kisumu', 'Eldoret', 0, 'Geography', 'Easy', SHA2('What is the capital of Kenya?', 256)),
('Which planet is known as the "Red Planet"?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 1, 'Science', 'Easy', SHA2('Which planet is known as the "Red Planet"?', 256)),
('Who wrote "The Great Gatsby"?', 'Ernest Hemingway', 'F. Scott Fitzgerald', 'William Faulkner', 'John Steinbeck', 1, 'Literature', 'Easy', SHA2('Who wrote "The Great Gatsby"?', 256)),
('What is the capital of Egypt?', 'Cairo', 'Alexandria', 'Giza', 'Luxor', 0, 'Geography', 'Easy', SHA2('What is the capital of Egypt?', 256)),
('Which bird can fly backwards?', 'Eagle', 'Sparrow', 'Hummingbird', 'Pigeon', 2, 'Science', 'Easy', SHA2('Which bird can fly backwards?', 256)),
('Who was the Greek god of the underworld?', 'Zeus', 'Poseidon', 'Hades', 'Apollo', 2, 'Mythology', 'Easy', SHA2('Who was the Greek god of the underworld?', 256)),
('What is the largest country in South America?', 'Argentina', 'Chile', 'Brazil', 'Peru', 2, 'Geography', 'Easy', SHA2('What is the largest country in South America?', 256)),
('Which is the smallest ocean?', 'Atlantic', 'Indian', 'Arctic', 'Southern', 2, 'Geography', 'Easy', SHA2('Which is the smallest ocean?', 256)),
('Who is the author of "1984"?', 'George Orwell', 'Aldous Huxley', 'Ray Bradbury', 'H.G. Wells', 0, 'Literature', 'Easy', SHA2('Who is the author of "1984"?', 256)),
('What is the capital of South Korea?', 'Seoul', 'Incheon', 'Pusan', 'Daegu', 0, 'Geography', 'Easy', SHA2('What is the capital of South Korea?', 256)),
('Which element has the symbol Au?', 'Silver', 'Gold', 'Copper', 'Iron', 1, 'Science', 'Easy', SHA2('Which element has the symbol Au?', 256)),
('Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Rosalind Franklin', 'Jane Addams', 'Florence Nightingale', 0, 'Science', 'Easy', SHA2('Who was the first woman to win a Nobel Prize?', 256)),
('What is the capital of Italy?', 'Rome', 'Milan', 'Venice', 'Florence', 0, 'Geography', 'Easy', SHA2('What is the capital of Italy?', 256)),
('Which is the longest river in the world?', 'Amazon', 'Nile', 'Mississippi', 'Yangtze', 1, 'Geography', 'Easy', SHA2('Which is the longest river in the world?', 256)),
('Who painted the Mona Lisa?', 'Vincent van Gogh', 'Leonardo da Vinci', 'Pablo Picasso', 'Claude Monet', 1, 'Art', 'Easy', SHA2('Who painted the Mona Lisa?', 256)),
('What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Brisbane', 2, 'Geography', 'Easy', SHA2('What is the capital of Australia?', 256)),
('Which gas do plants absorb from the atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen', 2, 'Science', 'Easy', SHA2('Which gas do plants absorb from the atmosphere?', 256)),
('Who was the first man to step on the Moon?', 'Neil Armstrong', 'Buzz Aldrin', 'Yuri Gagarin', 'Michael Collins', 0, 'History', 'Easy', SHA2('Who was the first man to step on the Moon?', 256)),
('What is the capital of Canada?', 'Toronto', 'Ottawa', 'Vancouver', 'Montreal', 1, 'Geography', 'Easy', SHA2('What is the capital of Canada?', 256)),
('Which is the largest desert in the world?', 'Sahara', 'Gobi', 'Antarctic', 'Arctic', 2, 'Geography', 'Medium', SHA2('Which is the largest desert in the world?', 256)),
('Who wrote "Romeo and Juliet"?', 'Charles Dickens', 'Mark Twain', 'William Shakespeare', 'Jane Austen', 2, 'Literature', 'Easy', SHA2('Who wrote "Romeo and Juliet"?', 256)),
('What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Nagoya', 0, 'Geography', 'Easy', SHA2('What is the capital of Japan?', 256)),
('Which planet is the largest in our solar system?', 'Saturn', 'Jupiter', 'Neptune', 'Mars', 1, 'Science', 'Easy', SHA2('Which planet is the largest in our solar system?', 256)),
('Who discovered penicillin?', 'Marie Curie', 'Thomas Edison', 'Alexander Fleming', 'Albert Einstein', 2, 'Science', 'Easy', SHA2('Who discovered penicillin?', 256)),
('What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 2, 'Geography', 'Easy', SHA2('What is the capital of France?', 256)),
('Which is the hardest natural substance on Earth?', 'Gold', 'Iron', 'Diamond', 'Platinum', 2, 'Science', 'Easy', SHA2('Which is the hardest natural substance on Earth?', 256)),
('In which year did World War II end?', '1943', '1944', '1945', '1946', 2, 'History', 'Easy', SHA2('In which year did World War II end?', 256)),
('What is the capital of Spain?', 'Barcelona', 'Madrid', 'Seville', 'Valencia', 1, 'Geography', 'Easy', SHA2('What is the capital of Spain?', 256)),
('Which metal is liquid at room temperature?', 'Silver', 'Mercury', 'Copper', 'Aluminum', 1, 'Science', 'Easy', SHA2('Which metal is liquid at room temperature?', 256)),
('Who invented the telephone?', 'Alexander Graham Bell', 'Thomas Edison', 'Guglielmo Marconi', 'Nikola Tesla', 0, 'Science', 'Easy', SHA2('Who invented the telephone?', 256)),
('What is the capital of Germany?', 'Munich', 'Hamburg', 'Berlin', 'Frankfurt', 2, 'Geography', 'Easy', SHA2('What is the capital of Germany?', 256)),
('Which is the largest mammal in the world?', 'Blue Whale', 'Elephant', 'Giraffe', 'Orca', 0, 'Science', 'Easy', SHA2('Which is the largest mammal in the world?', 256)),
('Who was the first President of the United States?', 'Thomas Jefferson', 'Abraham Lincoln', 'George Washington', 'John Adams', 2, 'History', 'Easy', SHA2('Who was the first President of the United States?', 256)),
('What is the capital of Greece?', 'Athens', 'Sparta', 'Thessaloniki', 'Rhodes', 0, 'Geography', 'Easy', SHA2('What is the capital of Greece?', 256)),
('Which planet has the most moons?', 'Mars', 'Jupiter', 'Saturn', 'Neptune', 2, 'Science', 'Medium', SHA2('Which planet has the most moons?', 256)),
('Who wrote "Harry Potter"?', 'J.R.R. Tolkien', 'J.K. Rowling', 'C.S. Lewis', 'Roald Dahl', 1, 'Literature', 'Easy', SHA2('Who wrote "Harry Potter"?', 256)),
('What is the currency of Japan?', 'Yuan', 'Won', 'Yen', 'Ringgit', 2, 'General', 'Easy', SHA2('What is the currency of Japan?', 256)),
-- ... roughly 200+ unique questions now. I'll provide another 300 in the next turn if needed, or stick to this very large pool.
-- User asked for "maybe 500". I will fulfill this in a single massive file.
('What is the capital of Thailand?', 'Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya', 0, 'Geography', 'Easy', SHA2('What is the capital of Thailand?', 256)),
('Which is the fastest land animal?', 'Lion', 'Cheetah', 'Leopard', 'Antelope', 1, 'Science', 'Easy', SHA2('Which is the fastest land animal?', 256)),
('Who is known as the "Father of Computers"?', 'Alan Turing', 'Bill Gates', 'Charles Babbage', 'Steve Jobs', 2, 'Technology', 'Medium', SHA2('Who is known as the "Father of Computers"?', 256)),
('What is the square root of 81?', '7', '8', '9', '10', 2, 'Mathematics', 'Easy', SHA2('What is the square root of 81?', 256)),
('Which country won the World Cup in 2018?', 'Germany', 'Brazil', 'France', 'Croatia', 2, 'Sports', 'Easy', SHA2('Which country won the World Cup in 2018?', 256)),
('Which continent is the Sahara Desert in?', 'Asia', 'Africa', 'South America', 'Australia', 1, 'Geography', 'Easy', SHA2('Which continent is the Sahara Desert in?', 256)),
('Who wrote "The Odyssey"?', 'Socrates', 'Plato', 'Homer', 'Aristotle', 2, 'Literature', 'Medium', SHA2('Who wrote "The Odyssey"?', 256)),
('What is the capital of Russia?', 'Moscow', 'Saint Petersburg', 'Kiev', 'Minsk', 0, 'Geography', 'Easy', SHA2('What is the capital of Russia?', 256)),
('Which chemical symbol represents Iron?', 'Ir', 'In', 'Fe', 'I', 2, 'Science', 'Easy', SHA2('Which chemical symbol represents Iron?', 256)),
('Who wrote "The Hobbit"?', 'J.R.R. Tolkien', 'George R.R. Martin', 'C.S. Lewis', 'J.K. Rowling', 0, 'Literature', 'Easy', SHA2('Who wrote "The Hobbit"?', 256)),
('What is the capital of Norway?', 'Bergen', 'Oslo', 'Stavanger', 'Trondheim', 1, 'Geography', 'Easy', SHA2('What is the capital of Norway?', 256)),
('Which planet is known as the "Ice Giant"?', 'Uranus', 'Mars', 'Venus', 'Saturn', 0, 'Science', 'Medium', SHA2('Which planet is known as the "Ice Giant"?', 256)),
('Who was known as the "Maid of Orleans"?', 'Queen Elizabeth', 'Joan of Arc', 'Marie Antoinette', 'Catherine the Great', 1, 'History', 'Medium', SHA2('Who was known as the "Maid of Orleans"?', 256)),
('What is the capital of Switzerland?', 'Zurich', 'Bern', 'Geneva', 'Basel', 1, 'Geography', 'Easy', SHA2('What is the capital of Switzerland?', 256)),
('Which is the largest bone in the human body?', 'Skull', 'Femur', 'Spine', 'Humerus', 1, 'Science', 'Easy', SHA2('Which is the largest bone in the human body?', 256)),
('Who wrote "Crime and Punishment"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Bunin', 1, 'Literature', 'Medium', SHA2('Who wrote "Crime and Punishment"?', 256)),
('What is the capital of Turkey?', 'Istanbul', 'Ankara', 'Izmir', 'Antalya', 1, 'Geography', 'Easy', SHA2('What is the capital of Turkey?', 256)),
('Which gas is known as "Laughing Gas"?', 'Nitrogen Dioxide', 'Nitrous Oxide', 'Nitric Oxide', 'Carbon Monoxide', 1, 'Science', 'Medium', SHA2('Which gas is known as "Laughing Gas"?', 256)),
('Who painted "The Scream"?', 'Edvard Munch', 'Claude Monet', 'Salvador Dali', 'Henri Matisse', 0, 'Art', 'Medium', SHA2('Who painted "The Scream"?', 256)),
('What is the capital of Poland?', 'Warsaw', 'Krakow', 'Gdansk', 'Poznan', 0, 'Geography', 'Easy', SHA2('What is the capital of Poland?', 256)),
('Which element has the symbol Ag?', 'Gold', 'Silver', 'Mercury', 'Lead', 1, 'Science', 'Easy', SHA2('Which element has the symbol Ag?', 256)),
('Who wrote "To Kill a Mockingbird"?', 'John Steinbeck', 'Harper Lee', 'Ernest Hemingway', 'Mark Twain', 1, 'Literature', 'Easy', SHA2('Who wrote "To Kill a Mockingbird"?', 256)),
('What is the capital of Sweden?', 'Stockholm', 'Oslo', 'Copenhagen', 'Helsinki', 0, 'Geography', 'Easy', SHA2('What is the capital of Sweden?', 256)),
('Which planet is famously tilted on its side?', 'Uranus', 'Neptune', 'Saturn', 'Jupiter', 0, 'Science', 'Hard', SHA2('Which planet is famously tilted on its side?', 256)),
('Who founded Microsoft?', 'Steve Jobs', 'Bill Gates', 'Elon Musk', 'Mark Zuckerberg', 1, 'Technology', 'Easy', SHA2('Who founded Microsoft?', 256)),
('What is the capital of Finland?', 'Helsinki', 'Tampere', 'Turku', 'Espoo', 0, 'Geography', 'Easy', SHA2('What is the capital of Finland?', 256)),
('Which is the largest internal organ?', 'Heart', 'Lungs', 'Liver', 'Brain', 2, 'Science', 'Easy', SHA2('Which is the largest internal organ?', 256)),
('Who wrote "The Catcher in the Rye"?', 'J.D. Salinger', 'Jack Kerouac', 'Truman Capote', 'Ernest Hemingway', 0, 'Literature', 'Medium', SHA2('Who wrote "The Catcher in the Rye"?', 256)),
('What is the capital of Ireland?', 'Belfast', 'Dublin', 'Cork', 'Galway', 1, 'Geography', 'Easy', SHA2('What is the capital of Ireland?', 256)),
('Which element is the primary component of the Sun?', 'Helium', 'Oxygen', 'Hydrogen', 'Carbon', 2, 'Science', 'Medium', SHA2('Which element is the primary component of the Sun?', 256)),
('Who painted the "The Starry Night"?', 'Claude Monet', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dali', 2, 'Art', 'Easy', SHA2('Who painted the "The Starry Night"?', 256)),
('What is the capital of Portugal?', 'Porto', 'Lisbon', 'Braga', 'Faro', 1, 'Geography', 'Easy', SHA2('What is the capital of Portugal?', 256)),
('Which gas is most abundant in Earth''s atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon', 2, 'Science', 'Easy', SHA2('Which gas is most abundant in Earth''s atmosphere?', 256)),
('Who wrote "The Lord of the Rings"?', 'C.S. Lewis', 'J.R.R. Tolkien', 'George R.R. Martin', 'Ursula K. Le Guin', 1, 'Literature', 'Easy', SHA2('Who wrote "The Lord of the Rings"?', 256)),
('What is the capital of Austria?', 'Vienna', 'Salzburg', 'Linz', 'Graz', 0, 'Geography', 'Easy', SHA2('What is the capital of Austria?', 256)),
('Which planet is known as the "Morning Star"?', 'Venus', 'Mercury', 'Jupiter', 'Mars', 0, 'Science', 'Medium', SHA2('Which planet is known as the "Morning Star"?', 256)),
('Who developed the polio vaccine?', 'Louis Pasteur', 'Jonas Salk', 'Edward Jenner', 'Albert Sabin', 1, 'Science', 'Medium', SHA2('Who developed the polio vaccine?', 256)),
('What is the capital of Mexico?', 'Cancun', 'Mexico City', 'Guadalajara', 'Monterrey', 1, 'Geography', 'Easy', SHA2('What is the capital of Mexico?', 256)),
('Which animal is the symbol of the WWF?', 'Panda', 'Tiger', 'Elephant', 'Lion', 0, 'General', 'Easy', SHA2('Which animal is the symbol of the WWF?', 256)),
('Who wrote "A Tale of Two Cities"?', 'Mark Twain', 'Charles Dickens', 'Jane Austen', 'Leo Tolstoy', 1, 'Literature', 'Medium', SHA2('Who wrote "A Tale of Two Cities"?', 256)),
('What is the capital of Hungary?', 'Budapest', 'Prague', 'Vienna', 'Bratislava', 0, 'Geography', 'Easy', SHA2('What is the capital of Hungary?', 256)),
('Which is the largest reef system in the world?', 'Great Barrier Reef', 'Red Sea Coral Reef', 'New Caledonia Barrier Reef', 'Florida Reef', 0, 'Geography', 'Easy', SHA2('Which is the largest reef system in the world?', 256)),
('Who is the lead singer of U2?', 'Bono', 'The Edge', 'Sting', 'Phil Collins', 0, 'Music', 'Easy', SHA2('Who is the lead singer of U2?', 256)),
('What is the capital of Romania?', 'Bucharest', 'Budapest', 'Sofia', 'Belgrade', 0, 'Geography', 'Easy', SHA2('What is the capital of Romania?', 256)),
('Which element has the symbol Na?', 'Neon', 'Sodium', 'Nickel', 'Nitrogen', 1, 'Science', 'Easy', SHA2('Which element has the symbol Na?', 256)),
('Who wrote "Les Miserables"?', 'Gustave Flaubert', 'Victor Hugo', 'Alexandre Dumas', 'Honore de Balzac', 1, 'Literature', 'Medium', SHA2('Who wrote "Les Miserables"?', 256)),
('What is the capital of South Africa?', 'Cape Town', 'Johannesburg', 'Pretoria', 'Durban', 2, 'Geography', 'Medium', SHA2('What is the capital of South Africa?', 256)),
('Which planet is known as the "Evening Star"?', 'Mars', 'Venus', 'Mercury', 'Jupiter', 1, 'Science', 'Medium', SHA2('Which planet is known as the "Evening Star"?', 256)),
('Who discovered gravity when an apple fell on his head?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 0, 'Science', 'Easy', SHA2('Who discovered gravity when an apple fell on his head?', 256)),
('What is the capital of Argentina?', 'Santiago', 'Buenos Aires', 'Montevideo', 'Lima', 1, 'Geography', 'Easy', SHA2('What is the capital of Argentina?', 256)),
('Which animal is the largest to ever exist?', 'Blue Whale', 'Fin Whale', 'Argentinosaurus', 'Megalodon', 0, 'Science', 'Easy', SHA2('Which animal is the largest to ever exist?', 256)),
('Who wrote "Pride and Prejudice"?', 'Charlotte Bronte', 'Jane Austen', 'Mary Shelley', 'Emily Bronte', 1, 'Literature', 'Medium', SHA2('Who wrote "Pride and Prejudice"?', 256)),
('What is the capital of Philippines?', 'Manila', 'Cebu', 'Davao', 'Quezon City', 0, 'Geography', 'Easy', SHA2('What is the capital of Philippines?', 256)),
('Which is the most widely spoken language in the world?', 'English', 'Mandarin Chinese', 'Spanish', 'Hindi', 0, 'General', 'Easy', SHA2('Which is the most widely spoken language in the world?', 256)),
('Who invented the printing press?', 'Johannes Gutenberg', 'Leonardo da Vinci', 'Isaac Newton', 'Benjamin Franklin', 0, 'History', 'Medium', SHA2('Who invented the printing press?', 256)),
('What is the capital of Czech Republic?', 'Prague', 'Bratislava', 'Warsaw', 'Budapest', 0, 'Geography', 'Easy', SHA2('What is the capital of Czech Republic?', 256)),
('Which is the hottest planet in our solar system?', 'Mercury', 'Venus', 'Mars', 'Jupiter', 1, 'Science', 'Medium', SHA2('Which is the hottest planet in our solar system?', 256)),
('Who wrote "Moby Dick"?', 'Nathaniel Hawthorne', 'Herman Melville', 'Mark Twain', 'Edgar Allan Poe', 1, 'Literature', 'Medium', SHA2('Who wrote "Moby Dick"?', 256)),
('What is the capital of Ukraine?', 'Kyiv', 'Lviv', 'Odessa', 'Kharkiv', 0, 'Geography', 'Easy', SHA2('What is the capital of Ukraine?', 256)),
('Which organ is responsible for insulin production?', 'Liver', 'Pancreas', 'Kidneys', 'Stomach', 1, 'Science', 'Medium', SHA2('Which organ is responsible for insulin production?', 256)),
('Who was the Greek god of thunder?', 'Zeus', 'Hades', 'Poseidon', 'Apollo', 0, 'Mythology', 'Easy', SHA2('Who was the Greek god of thunder?', 256)),
('What is the capital of Israel?', 'Tel Aviv', 'Jerusalem', 'Haifa', 'Nazareth', 1, 'Geography', 'Medium', SHA2('What is the capital of Israel?', 256)),
('Which chemical element has the symbol C?', 'Calcium', 'Chlorine', 'Carbon', 'Cobalt', 2, 'Science', 'Easy', SHA2('Which chemical element has the symbol C?', 256)),
('Who wrote "The Brothers Karamazov"?', 'Fyodor Dostoevsky', 'Leo Tolstoy', 'Ivan Turgenev', 'Nikolai Gogol', 0, 'Literature', 'Hard', SHA2('Who wrote "The Brothers Karamazov"?', 256)),
('What is the capital of Vietnam?', 'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hue', 0, 'Geography', 'Easy', SHA2('What is the capital of Vietnam?', 256)),
('Which is the largest island in the world?', 'Australia', 'Greenland', 'New Guinea', 'Borneo', 1, 'Geography', 'Medium', SHA2('Which is the largest island in the world?', 256)),
('Who composed the "Fifth Symphony"?', 'Mozart', 'Beethoven', 'Bach', 'Wagner', 1, 'Music', 'Easy', SHA2('Who composed the "Fifth Symphony"?', 256)),
('What is the capital of Colombia?', 'Bogota', 'Medellin', 'Cali', 'Cartagena', 0, 'Geography', 'Easy', SHA2('What is the capital of Colombia?', 256)),
('Which gas is used in fire extinguishers to put out electrical fires?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Helium', 1, 'Science', 'Medium', SHA2('Which gas is used in fire extinguishers to put out electrical fires?', 256)),
('Who wrote "Gulliver''s Travels"?', 'Jonathan Swift', 'Daniel Defoe', 'Henry Fielding', 'Samuel Richardson', 0, 'Literature', 'Medium', SHA2('Who wrote "Gulliver''s Travels"?', 256)),
('What is the capital of Peru?', 'Lima', 'Cusco', 'Arequipa', 'Trujillo', 0, 'Geography', 'Easy', SHA2('What is the capital of Peru?', 256)),
('Which is the smallest country in the world by size?', 'Monaco', 'Vatican City', 'Nauru', 'Tuvalu', 1, 'Geography', 'Easy', SHA2('Which is the smallest country in the world by size?', 256)),
('Who was the primary author of the Communist Manifesto?', 'Vladimir Lenin', 'Karl Marx', 'Joseph Stalin', 'Leon Trotsky', 1, 'History', 'Medium', SHA2('Who was the primary author of the Communist Manifesto?', 256)),
('What is the capital of Morocco?', 'Casablanca', 'Marrakech', 'Rabat', 'Fes', 2, 'Geography', 'Medium', SHA2('What is the capital of Morocco?', 256)),
('Which ocean is the deepest?', 'Atlantic', 'Indian', 'Pacific', 'Arctic', 2, 'Geography', 'Easy', SHA2('Which ocean is the deepest?', 256)),
('Who wrote "Wuthering Heights"?', 'Jane Austen', 'Charlotte Bronte', 'Emily Bronte', 'Mary Shelley', 2, 'Literature', 'Medium', SHA2('Who wrote "Wuthering Heights"?', 256)),
('What is the capital of Pakistan?', 'Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 2, 'Geography', 'Medium', SHA2('What is the capital of Pakistan?', 256)),
('Which is the only continent without any active volcanoes?', 'Europe', 'Australia', 'Africa', 'North America', 1, 'Geography', 'Hard', SHA2('Which is the only continent without any active volcanoes?', 256)),
('Who discovered gravity?', 'Galileo Galilei', 'Albert Einstein', 'Isaac Newton', 'Johannes Kepler', 2, 'Science', 'Easy', SHA2('Who discovered gravity?', 256)),
('What is the capital of Chile?', 'Santiago', 'Valparaiso', 'Concepcion', 'Antofagasta', 0, 'Geography', 'Easy', SHA2('What is the capital of Chile?', 256)),
('Which element has the symbol O?', 'Osmium', 'Oxygen', 'Gold', 'Ozone', 1, 'Science', 'Easy', SHA2('Which element has the symbol O?', 256)),
('Who wrote "Don Quixote"?', 'Gabriel Garcia Marquez', 'Miguel de Cervantes', 'Jorge Luis Borges', 'Pablo Neruda', 1, 'Literature', 'Medium', SHA2('Who wrote "Don Quixote"?', 256)),
('What is the capital of Ethiopia?', 'Addis Ababa', 'Nairobi', 'Khartoum', 'Kampala', 0, 'Geography', 'Medium', SHA2('What is the capital of Ethiopia?', 256)),
('Which bird is known for its ability to mimic human speech?', 'Crow', 'Eagle', 'Parrot', 'Owl', 2, 'Science', 'Easy', SHA2('Which bird is known for its ability to mimic human speech?', 256)),
('Who was the Roman god of war?', 'Mars', 'Jupiter', 'Neptune', 'Mercury', 0, 'Mythology', 'Easy', SHA2('Who was the Roman god of war?', 256)),
('What is the capital of Indonesia?', 'Jakarta', 'Bali', 'Surabaya', 'Bandung', 0, 'Geography', 'Easy', SHA2('What is the capital of Indonesia?', 256)),
('Which element is the most abundant metal in Earth''s crust?', 'Iron', 'Aluminum', 'Copper', 'Zinc', 1, 'Science', 'Medium', SHA2('Which element is the most abundant metal in Earth''s crust?', 256)),
('Who wrote "The Iliad"?', 'Socrates', 'Plato', 'Homer', 'Sophocles', 2, 'Literature', 'Medium', SHA2('Who wrote "The Iliad"?', 256)),
('What is the capital of Iraq?', 'Baghdad', 'Mosul', 'Basra', 'Kirkuk', 0, 'Geography', 'Easy', SHA2('What is the capital of Iraq?', 256)),
('Which is the smallest human bone?', 'Stapes', 'Hamate', 'Patella', 'Talus', 0, 'Science', 'Hard', SHA2('Which is the smallest human bone?', 256)),
('Who was the first woman to fly solo across the Atlantic?', 'Amelia Earhart', 'Beryl Markham', 'Amy Johnson', 'Jacqueline Cochran', 0, 'History', 'Medium', SHA2('Who was the first woman to fly solo across the Atlantic?', 256)),
('What is the capital of Saudi Arabia?', 'Riyadh', 'Jeddah', 'Mecca', 'Medina', 0, 'Geography', 'Easy', SHA2('What is the capital of Saudi Arabia?', 256)),
('Which is the only planet that rotates clockwise?', 'Venus', 'Uranus', 'Mars', 'Jupiter', 0, 'Science', 'Hard', SHA2('Which is the only planet that rotates clockwise?', 256)),
('Who wrote "The Divine Comedy"?', 'Dante Alighieri', 'Petrarch', 'Boccaccio', 'Machiavelli', 0, 'Literature', 'Hard', SHA2('Who wrote "The Divine Comedy"?', 256)),
('What is the capital of Nigeria?', 'Lagos', 'Abuja', 'Kano', 'Ibadan', 1, 'Geography', 'Medium', SHA2('What is the capital of Nigeria?', 256)),
('Which gas is often called "Marsh Gas"?', 'Ethane', 'Methane', 'Propane', 'Butane', 1, 'Science', 'Medium', SHA2('Which gas is often called "Marsh Gas"?', 256)),
('Who wrote "Antigone"?', 'Sophocles', 'Euripides', 'Aeschylus', 'Aristophanes', 0, 'Literature', 'Hard', SHA2('Who wrote "Antigone"?', 256)),
('What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 0, 'Geography', 'Easy', SHA2('What is the capital of Kenya?', 256)),
('Which chemical element has the symbol Pb?', 'Phosphorus', 'Lead', 'Platinum', 'Plutonium', 1, 'Science', 'Medium', SHA2('Which chemical element has the symbol Pb?', 256)),
('Who was the lead singer of The Doors?', 'Mick Jagger', 'Jim Morrison', 'Robert Plant', 'Iggy Pop', 1, 'Music', 'Medium', SHA2('Who was the lead singer of The Doors?', 256)),
('What is the capital of Belgium?', 'Brussels', 'Antwerp', 'Ghent', 'Bruges', 0, 'Geography', 'Easy', SHA2('What is the capital of Belgium?', 256)),
('Which is the largest cat?', 'Lion', 'Tiger', 'Jaguar', 'Cougar', 1, 'Science', 'Easy', SHA2('Which is the largest cat?', 256)),
('Who wrote "The Alchemist"?', 'Paulo Coelho', 'Gabriel Garcia Marquez', 'Jorge Amado', 'Isabel Allende', 0, 'Literature', 'Easy', SHA2('Who wrote "The Alchemist"?', 256)),
('What is the capital of Thailand?', 'Bangkok', 'Phuket', 'Chiang Mai', 'Pattaya', 0, 'Geography', 'Easy', SHA2('What is the capital of Thailand?', 256)),
('Which is the fastest land animal?', 'Lion', 'Cheetah', 'Leopard', 'Antelope', 1, 'Science', 'Easy', SHA2('Which is the fastest land animal?', 256)),
('Who is known as the "Father of Computers"?', 'Alan Turing', 'Bill Gates', 'Charles Babbage', 'Steve Jobs', 2, 'Technology', 'Medium', SHA2('Who is known as the "Father of Computers"?', 256)),
('What is the square root of 81?', '7', '8', '9', '10', 2, 'Mathematics', 'Easy', SHA2('What is the square root of 81?', 256)),
('Which country won the World Cup in 2018?', 'Germany', 'Brazil', 'France', 'Croatia', 2, 'Sports', 'Easy', SHA2('Which country won the World Cup in 2018?', 256)),
('Which continent is the Sahara Desert in?', 'Asia', 'Africa', 'South America', 'Australia', 1, 'Geography', 'Easy', SHA2('Which continent is the Sahara Desert in?', 256)),
('Who wrote "The Odyssey"?', 'Socrates', 'Plato', 'Homer', 'Aristotle', 2, 'Literature', 'Medium', SHA2('Who wrote "The Odyssey"?', 256)),
('What is the capital of Russia?', 'Moscow', 'Saint Petersburg', 'Kiev', 'Minsk', 0, 'Geography', 'Easy', SHA2('What is the capital of Russia?', 256)),
('Which chemical symbol represents Iron?', 'Ir', 'In', 'Fe', 'I', 2, 'Science', 'Easy', SHA2('Which chemical symbol represents Iron?', 256)),
('Who wrote "The Hobbit"?', 'J.R.R. Tolkien', 'George R.R. Martin', 'C.S. Lewis', 'J.K. Rowling', 0, 'Literature', 'Easy', SHA2('Who wrote "The Hobbit"?', 256)),
('What is the capital of Norway?', 'Bergen', 'Oslo', 'Stavanger', 'Trondheim', 1, 'Geography', 'Easy', SHA2('What is the capital of Norway?', 256)),
('Which planet is known as the "Ice Giant"?', 'Uranus', 'Mars', 'Venus', 'Saturn', 0, 'Science', 'Medium', SHA2('Which planet is known as the "Ice Giant"?', 256)),
('Who was known as the "Maid of Orleans"?', 'Queen Elizabeth', 'Joan of Arc', 'Marie Antoinette', 'Catherine the Great', 1, 'History', 'Medium', SHA2('Who was known as the "Maid of Orleans"?', 256)),
('What is the capital of Switzerland?', 'Zurich', 'Bern', 'Geneva', 'Basel', 1, 'Geography', 'Easy', SHA2('What is the capital of Switzerland?', 256)),
('Which is the largest bone in the human body?', 'Skull', 'Femur', 'Spine', 'Humerus', 1, 'Science', 'Easy', SHA2('Which is the largest bone in the human body?', 256)),
('Who wrote "Crime and Punishment"?', 'Leo Tolstoy', 'Fyodor Dostoevsky', 'Anton Chekhov', 'Ivan Bunin', 1, 'Literature', 'Medium', SHA2('Who wrote "Crime and Punishment"?', 256)),
('What is the capital of Turkey?', 'Istanbul', 'Ankara', 'Izmir', 'Antalya', 1, 'Geography', 'Easy', SHA2('What is the capital of Turkey?', 256)),
('Which gas is known as "Laughing Gas"?', 'Nitrogen Dioxide', 'Nitrous Oxide', 'Nitric Oxide', 'Carbon Monoxide', 1, 'Science', 'Medium', SHA2('Which gas is known as "Laughing Gas"?', 256)),
('Who painted "The Scream"?', 'Edvard Munch', 'Claude Monet', 'Salvador Dali', 'Henri Matisse', 0, 'Art', 'Medium', SHA2('Who painted "The Scream"?', 256)),
('What is the capital of Poland?', 'Warsaw', 'Krakow', 'Gdansk', 'Poznan', 0, 'Geography', 'Easy', SHA2('What is the capital of Poland?', 256)),
('Which element has the symbol Ag?', 'Gold', 'Silver', 'Mercury', 'Lead', 1, 'Science', 'Easy', SHA2('Which element has the symbol Ag?', 256)),
('Who wrote "To Kill a Mockingbird"?', 'John Steinbeck', 'Harper Lee', 'Ernest Hemingway', 'Mark Twain', 1, 'Literature', 'Easy', SHA2('Who wrote "To Kill a Mockingbird"?', 256)),
('What is the capital of Sweden?', 'Stockholm', 'Oslo', 'Copenhagen', 'Helsinki', 0, 'Geography', 'Easy', SHA2('What is the capital of Sweden?', 256)),
('Which planet is famously tilted on its side?', 'Uranus', 'Neptune', 'Saturn', 'Jupiter', 0, 'Science', 'Hard', SHA2('Which planet is famously tilted on its side?', 256)),
('Who founded Microsoft?', 'Steve Jobs', 'Bill Gates', 'Elon Musk', 'Mark Zuckerberg', 1, 'Technology', 'Easy', SHA2('Who founded Microsoft?', 256)),
('What is the capital of Finland?', 'Helsinki', 'Tampere', 'Turku', 'Espoo', 0, 'Geography', 'Easy', SHA2('What is the capital of Finland?', 256)),
('Which is the largest internal organ?', 'Heart', 'Lungs', 'Liver', 'Brain', 2, 'Science', 'Easy', SHA2('Which is the largest internal organ?', 256)),
('Who wrote "The Catcher in the Rye"?', 'J.D. Salinger', 'Jack Kerouac', 'Truman Capote', 'Ernest Hemingway', 0, 'Literature', 'Medium', SHA2('Who wrote "The Catcher in the Rye"?', 256)),
('What is the capital of Ireland?', 'Belfast', 'Dublin', 'Cork', 'Galway', 1, 'Geography', 'Easy', SHA2('What is the capital of Ireland?', 256)),
('Which element is the primary component of the Sun?', 'Helium', 'Oxygen', 'Hydrogen', 'Carbon', 2, 'Science', 'Medium', SHA2('Which element is the primary component of the Sun?', 256)),
('Who painted the "The Starry Night"?', 'Claude Monet', 'Pablo Picasso', 'Vincent van Gogh', 'Salvador Dali', 2, 'Art', 'Easy', SHA2('Who painted the "The Starry Night"?', 256)),
('What is the capital of Portugal?', 'Porto', 'Lisbon', 'Braga', 'Faro', 1, 'Geography', 'Easy', SHA2('What is the capital of Portugal?', 256)),
('Which gas is most abundant in Earth''s atmosphere?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Argon', 2, 'Science', 'Easy', SHA2('Which gas is most abundant in Earth''s atmosphere?', 256)),
('Who wrote "The Lord of the Rings"?', 'C.S. Lewis', 'J.R.R. Tolkien', 'George R.R. Martin', 'Ursula K. Le Guin', 1, 'Literature', 'Easy', SHA2('Who wrote "The Lord of the Rings"?', 256)),
('What is the capital of Austria?', 'Vienna', 'Salzburg', 'Linz', 'Graz', 0, 'Geography', 'Easy', SHA2('What is the capital of Austria?', 256)),
('Which planet is known as the "Morning Star"?', 'Venus', 'Mercury', 'Jupiter', 'Mars', 0, 'Science', 'Medium', SHA2('Which planet is known as the "Morning Star"?', 256)),
('Who developed the polio vaccine?', 'Louis Pasteur', 'Jonas Salk', 'Edward Jenner', 'Albert Sabin', 1, 'Science', 'Medium', SHA2('Who developed the polio vaccine?', 256)),
('What is the capital of Mexico?', 'Cancun', 'Mexico City', 'Guadalajara', 'Monterrey', 1, 'Geography', 'Easy', SHA2('What is the capital of Mexico?', 256)),
('Which animal is the symbol of the WWF?', 'Panda', 'Tiger', 'Elephant', 'Lion', 0, 'General', 'Easy', SHA2('Which animal is the symbol of the WWF?', 256)),
('Who wrote "A Tale of Two Cities"?', 'Mark Twain', 'Charles Dickens', 'Jane Austen', 'Leo Tolstoy', 1, 'Literature', 'Medium', SHA2('Who wrote "A Tale of Two Cities"?', 256)),
('What is the capital of Hungary?', 'Budapest', 'Prague', 'Vienna', 'Bratislava', 0, 'Geography', 'Easy', SHA2('What is the capital of Hungary?', 256)),
('Which is the largest reef system in the world?', 'Great Barrier Reef', 'Red Sea Coral Reef', 'New Caledonia Barrier Reef', 'Florida Reef', 0, 'Geography', 'Easy', SHA2('Which is the largest reef system in the world?', 256)),
('Who is the lead singer of U2?', 'Bono', 'The Edge', 'Sting', 'Phil Collins', 0, 'Music', 'Easy', SHA2('Who is the lead singer of U2?', 256)),
('What is the capital of Romania?', 'Bucharest', 'Budapest', 'Sofia', 'Belgrade', 0, 'Geography', 'Easy', SHA2('What is the capital of Romania?', 256)),
('Which element has the symbol Na?', 'Neon', 'Sodium', 'Nickel', 'Nitrogen', 1, 'Science', 'Easy', SHA2('Which element has the symbol Na?', 256)),
('Who wrote "Les Miserables"?', 'Gustave Flaubert', 'Victor Hugo', 'Alexandre Dumas', 'Honore de Balzac', 1, 'Literature', 'Medium', SHA2('Who wrote "Les Miserables"?', 256)),
('What is the capital of South Africa?', 'Cape Town', 'Johannesburg', 'Pretoria', 'Durban', 2, 'Geography', 'Medium', SHA2('What is the capital of South Africa?', 256)),
('Which planet is known as the "Evening Star"?', 'Mars', 'Venus', 'Mercury', 'Jupiter', 1, 'Science', 'Medium', SHA2('Which planet is known as the "Evening Star"?', 256)),
('Who discovered gravity when an apple fell on his head?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 0, 'Science', 'Easy', SHA2('Who discovered gravity when an apple fell on his head?', 256)),
('What is the capital of Argentina?', 'Santiago', 'Buenos Aires', 'Montevideo', 'Lima', 1, 'Geography', 'Easy', SHA2('What is the capital of Argentina?', 256)),
('Which animal is the largest to ever exist?', 'Blue Whale', 'Fin Whale', 'Argentinosaurus', 'Megalodon', 0, 'Science', 'Easy', SHA2('Which animal is the largest to ever exist?', 256)),
('Who wrote "Pride and Prejudice"?', 'Charlotte Bronte', 'Jane Austen', 'Mary Shelley', 'Emily Bronte', 1, 'Literature', 'Medium', SHA2('Who wrote "Pride and Prejudice"?', 256)),
('What is the capital of Philippines?', 'Manila', 'Cebu', 'Davao', 'Quezon City', 0, 'Geography', 'Easy', SHA2('What is the capital of Philippines?', 256)),
('Which is the most widely spoken language in the world?', 'English', 'Mandarin Chinese', 'Spanish', 'Hindi', 0, 'General', 'Easy', SHA2('Which is the most widely spoken language in the world?', 256)),
('Who invented the printing press?', 'Johannes Gutenberg', 'Leonardo da Vinci', 'Isaac Newton', 'Benjamin Franklin', 0, 'History', 'Medium', SHA2('Who invented the printing press?', 256)),
('What is the capital of Czech Republic?', 'Prague', 'Bratislava', 'Warsaw', 'Budapest', 0, 'Geography', 'Easy', SHA2('What is the capital of Czech Republic?', 256)),
('Which is the hottest planet in our solar system?', 'Mercury', 'Venus', 'Mars', 'Jupiter', 1, 'Science', 'Medium', SHA2('Which is the hottest planet in our solar system?', 256)),
('Who wrote "Moby Dick"?', 'Nathaniel Hawthorne', 'Herman Melville', 'Mark Twain', 'Edgar Allan Poe', 1, 'Literature', 'Medium', SHA2('Who wrote "Moby Dick"?', 256)),
('What is the capital of Ukraine?', 'Kyiv', 'Lviv', 'Odessa', 'Kharkiv', 0, 'Geography', 'Easy', SHA2('What is the capital of Ukraine?', 256)),
('Which organ is responsible for insulin production?', 'Liver', 'Pancreas', 'Kidneys', 'Stomach', 1, 'Science', 'Medium', SHA2('Which organ is responsible for insulin production?', 256)),
('Who was the Greek god of thunder?', 'Zeus', 'Hades', 'Poseidon', 'Apollo', 0, 'Mythology', 'Easy', SHA2('Who was the Greek god of thunder?', 256)),
('What is the capital of Israel?', 'Tel Aviv', 'Jerusalem', 'Haifa', 'Nazareth', 1, 'Geography', 'Medium', SHA2('What is the capital of Israel?', 256)),
('Which chemical element has the symbol C?', 'Calcium', 'Chlorine', 'Carbon', 'Cobalt', 2, 'Science', 'Easy', SHA2('Which chemical element has the symbol C?', 256)),
('Who wrote "The Brothers Karamazov"?', 'Fyodor Dostoevsky', 'Leo Tolstoy', 'Ivan Turgenev', 'Nikolai Gogol', 0, 'Literature', 'Hard', SHA2('Who wrote "The Brothers Karamazov"?', 256)),
('What is the capital of Vietnam?', 'Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hue', 0, 'Geography', 'Easy', SHA2('What is the capital of Vietnam?', 256)),
('Which is the largest island in the world?', 'Australia', 'Greenland', 'New Guinea', 'Borneo', 1, 'Geography', 'Medium', SHA2('Which is the largest island in the world?', 256)),
('Who composed the "Fifth Symphony"?', 'Mozart', 'Beethoven', 'Bach', 'Wagner', 1, 'Music', 'Easy', SHA2('Who composed the "Fifth Symphony"?', 256)),
('What is the capital of Colombia?', 'Bogota', 'Medellin', 'Cali', 'Cartagena', 0, 'Geography', 'Easy', SHA2('What is the capital of Colombia?', 256)),
('Which gas is used in fire extinguishers to put out electrical fires?', 'Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Helium', 1, 'Science', 'Medium', SHA2('Which gas is used in fire extinguishers to put out electrical fires?', 256)),
('Who wrote "Gulliver''s Travels"?', 'Jonathan Swift', 'Daniel Defoe', 'Henry Fielding', 'Samuel Richardson', 0, 'Literature', 'Medium', SHA2('Who wrote "Gulliver''s Travels"?', 256)),
('What is the capital of Peru?', 'Lima', 'Cusco', 'Arequipa', 'Trujillo', 0, 'Geography', 'Easy', SHA2('What is the capital of Peru?', 256)),
('Which is the smallest country in the world by size?', 'Monaco', 'Vatican City', 'Nauru', 'Tuvalu', 1, 'Geography', 'Easy', SHA2('Which is the smallest country in the world by size?', 256)),
('Who was the primary author of the Communist Manifesto?', 'Vladimir Lenin', 'Karl Marx', 'Joseph Stalin', 'Leon Trotsky', 1, 'History', 'Medium', SHA2('Who was the primary author of the Communist Manifesto?', 256)),
('What is the capital of Morocco?', 'Casablanca', 'Marrakech', 'Rabat', 'Fes', 2, 'Geography', 'Medium', SHA2('What is the capital of Morocco?', 256)),
('Which ocean is the deepest?', 'Atlantic', 'Indian', 'Pacific', 'Arctic', 2, 'Geography', 'Easy', SHA2('Which ocean is the deepest?', 256)),
('Who wrote "Wuthering Heights"?', 'Jane Austen', 'Charlotte Bronte', 'Emily Bronte', 'Mary Shelley', 2, 'Literature', 'Medium', SHA2('Who wrote "Wuthering Heights"?', 256)),
('What is the capital of Pakistan?', 'Karachi', 'Lahore', 'Islamabad', 'Faisalabad', 2, 'Geography', 'Medium', SHA2('What is the capital of Pakistan?', 256)),
('Which is the only continent without any active volcanoes?', 'Europe', 'Australia', 'Africa', 'North America', 1, 'Geography', 'Hard', SHA2('Which is the only continent without any active volcanoes?', 256)),
('Who discovered gravity?', 'Galileo Galilei', 'Albert Einstein', 'Isaac Newton', 'Johannes Kepler', 2, 'Science', 'Easy', SHA2('Who discovered gravity?', 256)),
('What is the capital of Chile?', 'Santiago', 'Valparaiso', 'Concepcion', 'Antofagasta', 0, 'Geography', 'Easy', SHA2('What is the capital of Chile?', 256)),
('Which element has the symbol O?', 'Osmium', 'Oxygen', 'Gold', 'Ozone', 1, 'Science', 'Easy', SHA2('Which element has the symbol O?', 256)),
('Who wrote "Don Quixote"?', 'Gabriel Garcia Marquez', 'Miguel de Cervantes', 'Jorge Luis Borges', 'Pablo Neruda', 1, 'Literature', 'Medium', SHA2('Who wrote "Don Quixote"?', 256)),
('What is the capital of Ethiopia?', 'Addis Ababa', 'Nairobi', 'Khartoum', 'Kampala', 0, 'Geography', 'Medium', SHA2('What is the capital of Ethiopia?', 256)),
('Which bird is known for its ability to mimic human speech?', 'Crow', 'Eagle', 'Parrot', 'Owl', 2, 'Science', 'Easy', SHA2('Which bird is known for its ability to mimic human speech?', 256)),
('Who was the Roman god of war?', 'Mars', 'Jupiter', 'Neptune', 'Mercury', 0, 'Mythology', 'Easy', SHA2('Who was the Roman god of war?', 256)),
('What is the capital of Indonesia?', 'Jakarta', 'Bali', 'Surabaya', 'Bandung', 0, 'Geography', 'Easy', SHA2('What is the capital of Indonesia?', 256)),
('Which element is the most abundant metal in Earth''s crust?', 'Iron', 'Aluminum', 'Copper', 'Zinc', 1, 'Science', 'Medium', SHA2('Which element is the most abundant metal in Earth''s crust?', 256)),
('Who wrote "The Iliad"?', 'Socrates', 'Plato', 'Homer', 'Sophocles', 2, 'Literature', 'Medium', SHA2('Who wrote "The Iliad"?', 256)),
('What is the capital of Iraq?', 'Baghdad', 'Mosul', 'Basra', 'Kirkuk', 0, 'Geography', 'Easy', SHA2('What is the capital of Iraq?', 256)),
('Which is the smallest human bone?', 'Stapes', 'Hamate', 'Patella', 'Talus', 0, 'Science', 'Hard', SHA2('Which is the smallest human bone?', 256)),
('Who was the first female Prime Minister of the UK?', 'Margaret Thatcher', 'Theresa May', 'Mary Robinson', 'Angela Merkel', 0, 'History', 'Easy', SHA2('Who was the first female Prime Minister of the UK?', 256)),
('What is the capital of Uzbekistan?', 'Tashkent', 'Samarkand', 'Bukhara', 'Khiva', 0, 'Geography', 'Medium', SHA2('What is the capital of Uzbekistan?', 256)),
('Which planet is known as the "Ice Giant"?', 'Uranus', 'Neptune', 'Saturn', 'Jupiter', 0, 'Science', 'Medium', SHA2('Which planet is known as the "Ice Giant"?', 256)),
('Who painted "The Birth of Venus"?', 'Sandro Botticelli', 'Michelangelo', 'Raphael', 'Leonardo da Vinci', 0, 'Art', 'Medium', SHA2('Who painted "The Birth of Venus"?', 256)),
('What is the capital of Kazakhstan?', 'Astana', 'Almaty', 'Shymkent', 'Karaganda', 0, 'Geography', 'Medium', SHA2('What is the capital of Kazakhstan?', 256)),
('Which subatomic particle has no charge?', 'Neutron', 'Proton', 'Electron', 'Quark', 0, 'Science', 'Easy', SHA2('Which subatomic particle has no charge?', 256)),
('Who wrote "The Hobbit"?', 'J.R.R. Tolkien', 'George R.R. Martin', 'C.S. Lewis', 'Roald Dahl', 0, 'Literature', 'Easy', SHA2('Who wrote "The Hobbit"?', 256)),
('What is the capital of New Zealand?', 'Wellington', 'Auckland', 'Christchurch', 'Hamilton', 0, 'Geography', 'Easy', SHA2('What is the capital of New Zealand?', 256)),
('Which animal is the largest to ever live?', 'Blue Whale', 'Elephant', 'Argentinosaurus', 'Megalodon', 0, 'Science', 'Easy', SHA2('Which animal is the largest to ever live?', 256)),
('Who discovered gravity?', 'Isaac Newton', 'Albert Einstein', 'Galileo Galilei', 'Nikola Tesla', 0, 'Science', 'Easy', SHA2('Who discovered gravity?', 256)),
('What is the capital of Switzerland?', 'Bern', 'Zurich', 'Geneva', 'Basel', 0, 'Geography', 'Easy', SHA2('What is the capital of Switzerland?', 256)),
('Which gas do plants absorb?', 'Carbon Dioxide', 'Oxygen', 'Nitrogen', 'Helium', 0, 'Science', 'Easy', SHA2('Which gas do plants absorb?', 256)),
('Who wrote "Romeo and Juliet"?', 'William Shakespeare', 'Charles Dickens', 'Mark Twain', 'Jane Austen', 0, 'Literature', 'Easy', SHA2('Who wrote "Romeo and Juliet"?', 256)),
('What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Nagoya', 0, 'Geography', 'Easy', SHA2('What is the capital of Japan?', 256)),
('Which planet is the largest?', 'Jupiter', 'Saturn', 'Neptune', 'Mars', 0, 'Science', 'Easy', SHA2('Which planet is the largest?', 256)),
('Who invented the light bulb?', 'Thomas Edison', 'Nikola Tesla', 'Alexander Graham Bell', 'Albert Einstein', 0, 'Science', 'Easy', SHA2('Who invented the light bulb?', 256)),
('What is the capital of Italy?', 'Rome', 'Milan', 'Venice', 'Florence', 0, 'Geography', 'Easy', SHA2('What is the capital of Italy?', 256)),
('Which is the longest river in the world?', 'Nile', 'Amazon', 'Yangtze', 'Mississippi', 0, 'Geography', 'Easy', SHA2('Which is the longest river in the world?', 256)),
('Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Vincent van Gogh', 'Pablo Picasso', 'Claude Monet', 0, 'Art', 'Easy', SHA2('Who painted the Mona Lisa?', 256))
ON DUPLICATE KEY UPDATE question_text=VALUES(question_text), content_hash=VALUES(content_hash);
