-- Migration: V8__add_sa_questions.sql
-- South Africa specific trivia questions.

INSERT INTO questions (question_text, option_a, option_b, option_c, option_d, correct_index, category, difficulty, region, content_hash) VALUES
('Who is the current President of South Africa?', 'Cyril Ramaphosa', 'Jacob Zuma', 'Thabo Mbeki', 'Kgalema Motlanthe', 0, 'Politics', 'Easy', 'south_africa', SHA2('Who is the current President of South Africa?', 256)),
('What is the legislative capital of South Africa?', 'Pretoria', 'Bloemfontein', 'Cape Town', 'Johannesburg', 2, 'Geography', 'Easy', 'south_africa', SHA2('What is the legislative capital of South Africa?', 256)),
('Which mountain is a famous landmark in Cape Town?', 'Drakensberg', 'Table Mountain', 'Lion''s Head', 'Signal Hill', 1, 'Geography', 'Easy', 'south_africa', SHA2('Which mountain is a famous landmark in Cape Town?', 256)),
('In which year did South Africa host the FIFA World Cup?', '2006', '2010', '2014', '2018', 1, 'Sports', 'Easy', 'south_africa', SHA2('In which year did the FIFA World Cup take place in SA?', 256)),
('What is the national flower of South Africa?', 'Rose', 'Protea', 'Daisy', 'Aloe', 1, 'General', 'Easy', 'south_africa', SHA2('What is the national flower of South Africa?', 256)),
('Which South African city is known as the "City of Gold"?', 'Durban', 'Cape Town', 'Johannesburg', 'Pretoria', 2, 'Geography', 'Easy', 'south_africa', SHA2('Which SA city is the City of Gold?', 256)),
('What is the currency of South Africa?', 'Dollar', 'Pound', 'Rand', 'Euro', 2, 'General', 'Easy', 'south_africa', SHA2('What is the currency of South Africa?', 256)),
('Who was the first black President of South Africa?', 'Desmond Tutu', 'Nelson Mandela', 'Oliver Tambo', 'Walter Sisulu', 1, 'History', 'Easy', 'south_africa', SHA2('Who was the first black President of SA?', 256)),
('Which province is the smallest in land area?', 'Gauteng', 'Limpopo', 'Free State', 'Mpumalanga', 0, 'Geography', 'Medium', 'south_africa', SHA2('Which province is the smallest in land area?', 256)),
('What is the nickname of the South African national rugby team?', 'Proteas', 'Bafana Bafana', 'Springboks', 'Blitzboks', 2, 'Sports', 'Easy', 'south_africa', SHA2('What is the nickname of the SA national rugby team?', 256)),
('Which ocean is on the east coast of South Africa?', 'Atlantic Ocean', 'Indian Ocean', 'Southern Ocean', 'Pacific Ocean', 1, 'Geography', 'Easy', 'south_africa', SHA2('Which ocean is on the east coast of South Africa?', 256)),
('What is the administrative capital of South Africa?', 'Cape Town', 'Bloemfontein', 'Pretoria', 'Johannesburg', 2, 'Geography', 'Easy', 'south_africa', SHA2('What is the administrative capital of South Africa?', 256)),
('Which South African won the Nobel Peace Prize in 1984?', 'Nelson Mandela', 'F.W. de Klerk', 'Desmond Tutu', 'Albert Luthuli', 2, 'History', 'Medium', 'south_africa', SHA2('Which SA person won Nobel Peace Prize 1984?', 256)),
('What is the largest park in South Africa?', 'Hluhluwe', 'Kruger National Park', 'Addo Elephant', 'Kgalagadi', 1, 'Geography', 'Easy', 'south_africa', SHA2('What is the largest park in South Africa?', 256)),
('Which language is most widely spoken as a first language in SA?', 'English', 'Afrikaans', 'isiZulu', 'isiXhosa', 2, 'General', 'Medium', 'south_africa', SHA2('Which language is most widely spoken as a first language in SA?', 256)),
('In which province is the Kruger National Park mainly located?', 'Limpopo & Mpumalanga', 'Gauteng', 'KwaZulu-Natal', 'North West', 0, 'Geography', 'Easy', 'south_africa', SHA2('Where is Kruger National Park located?', 256)),
('What is the judicial capital of South Africa?', 'Pretoria', 'Cape Town', 'Bloemfontein', 'Johannesburg', 2, 'Geography', 'Medium', 'south_africa', SHA2('What is the judicial capital of South Africa?', 256)),
('Which South African river forms the border with Zimbabwe?', 'Orange River', 'Vaul River', 'Limpopo River', 'Fish River', 2, 'Geography', 'Medium', 'south_africa', SHA2('Which SA river forms the border with Zimbabwe?', 256)),
('Who composed the national anthem "Nkosi Sikelel'' iAfrika"?', 'Enoch Sontonga', 'Sol Plaatje', 'Miriam Makeba', 'Brenda Fassie', 0, 'History', 'Hard', 'south_africa', SHA2('Who composed Nkosi Sikelel iAfrika?', 256)),
('What is the national animal of South Africa?', 'Lion', 'Elephant', 'Springbok', 'Leopard', 2, 'General', 'Easy', 'south_africa', SHA2('What is the national animal of South Africa?', 256)),
('Which South African city was previously called Port Elizabeth?', 'East London', 'Durban', 'Gqeberha', 'George', 2, 'Geography', 'Medium', 'south_africa', SHA2('Which SA city was Port Elizabeth?', 256)),
('What is the nickname of the South African national soccer team?', 'Springboks', 'Proteas', 'Bafana Bafana', 'Blitzboks', 2, 'Sports', 'Easy', 'south_africa', SHA2('What is the nickname of the SA soccer team?', 256)),
('In which year was Nelson Mandela released from prison?', '1989', '1990', '1991', '1992', 1, 'History', 'Medium', 'south_africa', SHA2('When was Nelson Mandela released?', 256)),
('Which desert covers part of the Northern Cape?', 'Sahara', 'Kalahari', 'Namib', 'Gobi', 1, 'Geography', 'Easy', 'south_africa', SHA2('Which desert in Northern Cape?', 256)),
('What is the tallest building in South Africa?', 'Ponte Tower', 'The Leonardo', 'Carlton Centre', 'Michangelo', 1, 'General', 'Hard', 'south_africa', SHA2('Tallest building in South Africa?', 256)),
('Which South African province is known as the "Garden Province"?', 'Western Cape', 'KwaZulu-Natal', 'Eastern Cape', 'Gauteng', 1, 'Geography', 'Medium', 'south_africa', SHA2('Which province is Garden Province?', 256)),
('Which South African town is famous for whale watching?', 'Knysna', 'Hermanus', 'Cape Town', 'Durban', 1, 'Geography', 'Easy', 'south_africa', SHA2('Which SA town famous for whales?', 256)),
('Who was the last apartheid-era president of South Africa?', 'P.W. Botha', 'F.W. de Klerk', 'John Vorster', 'Hendrik Verwoerd', 1, 'History', 'Medium', 'south_africa', SHA2('Last apartheid-era president?', 256)),
('What is the national bird of South Africa?', 'Ostrich', 'Blue Crane', 'African Fish Eagle', 'Penguin', 1, 'General', 'Medium', 'south_africa', SHA2('National bird of South Africa?', 256)),
('Which South African singer was known as "Mama Africa"?', 'Brenda Fassie', 'Miriam Makeba', 'Yvonne Chaka Chaka', 'Lira', 1, 'Music', 'Medium', 'south_africa', SHA2('Who was Mama Africa?', 256)),
('What is the name of the world-famous cave system in Krugersdorp?', 'Cango Caves', 'Sterkfontein Caves', 'Echo Caves', 'Wonder Cave', 1, 'Geography', 'Medium', 'south_africa', SHA2('Caves in Krugersdorp?', 256)),
('Which South African holiday is celebrated on June 16th?', 'Human Rights Day', 'Heritage Day', 'Youth Day', 'Freedom Day', 2, 'Culture', 'Easy', 'south_africa', SHA2('What is June 16th?', 256)),
('Which port is the busiest in South Africa and Africa?', 'Port Elizabeth', 'Cape Town', 'Durban', 'Richard''s Bay', 2, 'Geography', 'Hard', 'south_africa', SHA2('Busiest port in SA?', 256)),
('Who was the leader of the Zulu nation during the Battle of Isandlwana?', 'Shaka Zulu', 'Cetshwayo', 'Dingane', 'Mpande', 1, 'History', 'Hard', 'south_africa', SHA2('Zulu leader at Isandlwana?', 256)),
('What is the main grape used in the South African red wine Pinotage?', 'Merlot and Shiraz', 'Pinot Noir and Hermitage', 'Cabernet and Malbec', 'Grenache and Syrah', 1, 'General', 'Hard', 'south_africa', SHA2('Pinotage grapes?', 256)),
('Which province hosts the Comrades Marathon?', 'Gauteng', 'KwaZulu-Natal', 'Western Cape', 'Free State', 1, 'Sports', 'Easy', 'south_africa', SHA2('Where is Comrades Marathon?', 256)),
('What was the name of the first South African heart transplant surgeon?', 'Sydney Cywes', 'Christiaan Barnard', 'Hamilton Naki', 'Joe Anne de la Rey', 1, 'History', 'Easy', 'south_africa', SHA2('Who did first heart transplant?', 256)),
('Which city is the capital of the Free State?', 'Pretoria', 'Kimberley', 'Bloemfontein', 'Welkom', 2, 'Geography', 'Easy', 'south_africa', SHA2('Free State capital?', 256)),
('What is the name of the South African national cricket team?', 'Springboks', 'Proteas', 'Bafana Bafana', 'Blitzboks', 1, 'Sports', 'Easy', 'south_africa', SHA2('SA cricket team nickname?', 256)),
('In which year was the current South African flag adopted?', '1992', '1994', '1996', '1998', 1, 'History', 'Easy', 'south_africa', SHA2('When was the current SA flag adopted?', 256)),
('What is the name of the large crater in the Free State?', 'Vredefort Crater', 'Tswaing Crater', 'Kalkkop Crater', 'Morokweng Crater', 0, 'Geography', 'Hard', 'south_africa', SHA2('Vredefort Crater?', 256)),
('Which South African city is the primary hub of the diamond industry?', 'Johannesburg', 'Kimberley', 'Pretoria', 'Alexander Bay', 1, 'Geography', 'Medium', 'south_africa', SHA2('SA diamond industry hub?', 256)),
('What is the name of the South African holiday celebrated on September 24th?', 'Youth Day', 'Freedom Day', 'Heritage Day', 'Human Rights Day', 2, 'Culture', 'Easy', 'south_africa', SHA2('What is September 24th?', 256)),
('Which South African island served as a prison for political prisoners?', 'Dyer Island', 'Seal Island', 'Robben Island', 'Marion Island', 2, 'History', 'Easy', 'south_africa', SHA2('Robben Island prison?', 256)),
('What is the national tree of South Africa?', 'Baobab', 'Real Yellowwood', 'Marula', 'Mopane', 1, 'General', 'Hard', 'south_africa', SHA2('National tree of South Africa?', 256)),
('Which mountain range forms the border between KwaZulu-Natal and Lesotho?', 'Magaliesberg', 'Drakensberg', 'Cederberg', 'Outeniqua', 1, 'Geography', 'Medium', 'south_africa', SHA2('Drakensberg border?', 256)),
('What is the name of the South African national women''s soccer team?', 'Proteas', 'Banyana Banyana', 'Springboks', 'Bafana Bafana', 1, 'Sports', 'Easy', 'south_africa', SHA2('SA women soccer team nickname?', 256)),
('Which South African won the Nobel Prize for Literature in 1991?', 'J.M. Coetzee', 'Nadine Gordimer', 'Zakes Mda', 'Breyten Breytenbach', 1, 'Literature', 'Hard', 'south_africa', SHA2('Nadine Gordimer Nobel Prize?', 256)),
('What is the name of the large nature reserve in the Eastern Cape?', 'Addo Elephant Park', 'Augrabies Falls', 'Golden Gate', 'Table Mountain', 0, 'Geography', 'Medium', 'south_africa', SHA2('Addo Elephant Park Eastern Cape?', 256)),
('Which South African holiday is celebrated on April 27th?', 'Human Rights Day', 'Heritage Day', 'Freedom Day', 'Youth Day', 2, 'History', 'Easy', 'south_africa', SHA2('What is April 27th?', 256)),
('Who is known as the "Tinkerbell" of South African swimming?', 'Penny Heyns', 'Charlene Wittstock', 'Tatjana Smith', 'Natalie du Toit', 0, 'Sports', 'Hard', 'south_africa', SHA2('Penny Heyns swimming?', 256))
ON DUPLICATE KEY UPDATE question_text=VALUES(question_text), content_hash=VALUES(content_hash);
