-- More South Africa Trivia Questions
-- Flyway migration: V9__more_south_africa_questions.sql
-- Using INSERT IGNORE to skip any duplicates from previous migrations

INSERT IGNORE INTO questions (question_text, option_a, option_b, option_c, option_d, correct_index, category, difficulty, region, content_hash) VALUES
('Which South African city is known as the "Mother City"?', 'Johannesburg', 'Durban', 'Cape Town', 'Pretoria', 2, 'Geography', 'easy', 'south_africa', SHA2('Which South African city is known as the "Mother City"?', 256)),
('Which famous South African leader won the Nobel Peace Prize in 1993 alongside F.W. de Klerk?', 'Desmond Tutu', 'Nelson Mandela', 'Thabo Mbeki', 'Jacob Zuma', 1, 'History', 'easy', 'south_africa', SHA2('Which famous South African leader won the Nobel Peace Prize in 1993 alongside F.W. de Klerk?', 256)),
('Which desert covers a large part of the Northern Cape province?', 'Sahara', 'Kalahari', 'Namib', 'Gobi', 1, 'Geography', 'medium', 'south_africa', SHA2('Which desert covers a large part of the Northern Cape province?', 256)),
('What is the name of the largest hospital in Africa, located in Soweto?', 'Groote Schuur', 'Chris Hani Baragwanath', 'Charlotte Maxeke', 'Helen Joseph', 1, 'General', 'medium', 'south_africa', SHA2('What is the name of the largest hospital in Africa, located in Soweto?', 256)),
('Which mountain range is the highest in South Africa?', 'Drakensberg', 'Cederberg', 'Magaliesberg', 'Outeniqua', 0, 'Geography', 'medium', 'south_africa', SHA2('Which mountain range is the highest in South Africa?', 256)),
('Which South African province is the smallest by land area?', 'Gauteng', 'Mpumalanga', 'Western Cape', 'Free State', 0, 'Geography', 'medium', 'south_africa', SHA2('Which South African province is the smallest by land area?', 256)),
('Who is known as the "Queen of African Pop" and was a South African singer-songwriter?', 'Miriam Makeba', 'Brenda Fassie', 'Yvonne Chaka Chaka', 'Lira', 1, 'Music', 'medium', 'south_africa', SHA2('Who is known as the "Queen of African Pop" and was a South African singer-songwriter?', 256)),
('Which bridge in South Africa is the highest bungee jumping bridge in the world?', 'Storms River Bridge', 'Bloukrans Bridge', 'Nelson Mandela Bridge', 'Gourits River Bridge', 1, 'Tourism', 'medium', 'south_africa', SHA2('Which bridge in South Africa is the highest bungee jumping bridge in the world?', 256)),
('Which South African Nobel laureate wrote the novel "Disgrace"?', 'Nadine Gordimer', 'J.M. Coetzee', 'Alan Paton', 'Breyten Breytenbach', 1, 'Literature', 'hard', 'south_africa', SHA2('Which South African Nobel laureate wrote the novel "Disgrace"?', 256)),
('What is the name of the famous street in Soweto where two Nobel Peace Prize winners once lived?', 'Vilakazi Street', 'Mandela Road', 'Tutu Avenue', 'Sisulu Street', 0, 'History', 'medium', 'south_africa', SHA2('What is the name of the famous street in Soweto where two Nobel Peace Prize winners once lived?', 256)),
('Which South African rugby player is often called "The Beast"?', 'Siya Kolisi', 'Tendai Mtawarira', 'Eben Etzebeth', 'Cheslin Kolbe', 1, 'Sport', 'medium', 'south_africa', SHA2('Which South African rugby player is often called "The Beast"?', 256)),
('Which port is the busiest in South Africa and Africa?', 'Port Elizabeth', 'Durban', 'Cape Town', 'East London', 1, 'General', 'medium', 'south_africa', SHA2('Which port is the busiest in South Africa and Africa?', 256)),
('What was the name of the Zulu King who led his nation during the Battle of Isandlwana?', 'Shaka', 'Cetshwayo', 'Dingane', 'Zwelithini', 1, 'History', 'medium', 'south_africa', SHA2('What was the name of the Zulu King who led his nation during the Battle of Isandlwana?', 256)),
('Which South African city is the primary hub of the diamond industry?', 'Johannesburg', 'Kimberley', 'Pretoria', 'Springbok', 1, 'General', 'medium', 'south_africa', SHA2('Which South African city is the primary hub of the diamond industry?', 256)),
('What is the name of the world''s largest diamond discovered in SA in 1905?', 'Hope Diamond', 'Cullinan Diamond', 'Millennium Star', 'Koh-i-Noor', 1, 'History', 'hard', 'south_africa', SHA2('What is the name of the world''s largest diamond discovered in SA in 1905?', 256)),
('Which SA company is one of the world''s largest brewers?', 'Distell', 'SAB (South African Breweries)', 'Castle', 'Windhoek', 1, 'General', 'medium', 'south_africa', SHA2('Which SA company is one of the world''s largest brewers?', 256)),
('Which SA actor played the lead role in the film "District 9"?', 'Charlize Theron', 'Sharlto Copley', 'John Kani', 'Cliff Simon', 1, 'Entertainment', 'medium', 'south_africa', SHA2('Which SA actor played the lead role in the film "District 9"?', 256)),
('What is the name of the oldest winery in South Africa?', 'Spier', 'Groot Constantia', 'Nederburg', 'Kanonkop', 1, 'History', 'hard', 'south_africa', SHA2('What is the name of the oldest winery in South Africa?', 256)),
('Which South African inventor created the "Kreepy Krauly" pool cleaner?', 'Ferdinand Chauvier', 'Mark Shuttleworth', 'Elon Musk', 'Percy Tucker', 0, 'Science', 'hard', 'south_africa', SHA2('Which South African inventor created the "Kreepy Krauly" pool cleaner?', 256)),
('What is the name of the first South African satellite launched into space?', 'Sunsat', 'Zaspace', 'AfriSat', 'Tebogo', 0, 'Science', 'hard', 'south_africa', SHA2('What is the name of the first South African satellite launched into space?', 256));
